### DISCUSSION TITLE
Split domain deployments

### DISCUSSION THREAD

**Discussion by madx** [strapi/strapi#6743] [Legacy Topics]
Hi,

I want to do a split-domain deployment, a bit like the sub-folder one that is explained at https://strapi.io/documentation/v3.x/deployment/nginx-proxy.html

I am using nginx as a proxy, I'm launching nginx and strapi inside containers, orchestrated by a docker-compose file.

I would like to have the API available at `https://api.domain.com/` and the admin available at `https://admin.domain.com`. My current setup is as follows

```js
// strapi/config/server.js
module.exports = ({ env }) => ({
  host: env("HOST", "0.0.0.0"),
  port: env.int("PORT", 1337),
  url: env("STRAPI_API_URL"),
  admin: {
    url: env("STRAPI_ADMIN_URL"),
  },
})
```

```shell
# deploy/dev/strapi.env
STRAPI_API_URL=https://api.domain.com/
STRAPI_ADMIN_URL=https://admin.domain.com/
```

```nginx
# deploy/dev/nginx.conf
server {
  listen 80;
  server_name api.domain.com;

  location / {
    include proxy.conf;
    proxy_pass http://strapi:1337/;
  }
}

server {
  listen 80;
  server_name admin.domain.com;

  location / {
    include proxy.conf;
    proxy_pass http://strapi:1337/admin/;
  }
}
```

```yaml
# deploy/docker-compose.yml
version: "3"
services:
  strapi:
    image: strapi/strapi
    user: $UID:$GID
    volumes:
      - ../strapi/:/srv/app
    env_file: ./dev/strapi.env

  proxy:
    image: nginx
    volumes:
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dev/proxy.snippet.conf:/etc/nginx/proxy.conf
    restart: unless-stopped
    depends_on:
      - strapi
    ports:
      - "8000:80"
```

I tried many combinations and URLs but I always end up on a blank page with a message in the console saying that it can't parse the JS bundles. After checking the JS bundles URLs are returning the base HTML of the admin panel.

Is it possible to do this?
