### DISCUSSION TITLE
Deploying with Traefik yields 404 for admin panel

### DISCUSSION THREAD

**Discussion by vardy** [strapi/strapi#8041] [Legacy Topics]
Hi everyone, I recently tried to proxy Strapi with Traefik, however, I can't seem to figure out how to get the proxy to properly pass to Strapi's server - after spinning up my `docker-compose`, going to `cms.example.com/admin` throws a 404.

Traefik compose file: https://github.com/vardy/web-traefik/blob/master/docker-compose.yml

```yml
# docker-compose.yml
version: '3.7'

services:
#...
  cms:
    image: strapi/strapi
    env_file: .env
    volumes:
      - ./STRAPI_APP_CONTENT:/srv/app
    depends_on:
      - db
    networks:
     - web
     - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.arapiles-cms-web.rule=Host(`cms.example.org`))"
      - "traefik.http.routers.arapiles-cms-web.entrypoints=web"
      - "traefik.http.routers.arapiles-cms-web.middlewares=redirect@file"
      - "traefik.http.routers.arapiles-cms-secured.rule=Host(`cms.example.org`))"
      - "traefik.http.routers.arapiles-cms-secured.entrypoints=web-secured"
      - "traefik.http.routers.arapiles-cms-secured.tls.certresolver=mytlschallenge"
      - "traefik.http.services.arapiles-cms.loadbalancer.server.port=1337"

  db:
    image: mongo
    # ...

networks:
  web:
    external: true
  backend:
    external: false
```

```js
// /config/server.js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: 'https://cms.example.org',
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', 'secret'),
    },
  },
});
```

Anyone have any ideas?
I'm using the same config for other websites on the same server and they're working perfectly.
