### ISSUE TITLE
Get necessary Pagination meta data when returning a Collection Type

### ISSUE THREAD

**Issue by pratik149** [strapi/strapi#10162]
### Please describe your feature request

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

A toggle to enable/disable Pagination in Advanced Settings of a Collection Type, so as to get necessary pagination meta data and links when returning a collection.

### Why is it needed?

Implementing pagination in the frontend is painful and time consuming task. It is a very common requirement for many Collection Types. Currently we can make use of "_start" and "_limit" query parameters, but something as common as Pagination should be straight forward and easy to use. After coming from Laravel, I was surprised to know that this feature is missing in such a sophisticated tool like Strapi.

The data required to implement any kind of pagination is quite standardized now. Therefore, it would be really good to calculate and get all the necessary pagination data of a Collection Type in the API itself. This will save a lot of code in the frontend.

### Suggested solution(s)

Currently many giant frameworks like Laravel provide elegant methods for enabling Pagination in the API. In Strapi what I'm asking for is a toggle in the "Advanced Settings" of a Collection Type to enable/disable pagination system, and return the data accordingly. We can then also give a query parameter like "_perPage" with default value as 10.

Roughly this is how it will look like in the Admin Panel.

![Pagination Toggle](https://user-images.githubusercontent.com/31278436/116277673-560afa80-a7a3-11eb-8705-a090388e21b6.PNG)

When Disabled the API will return regular collection like below.

```yaml
// Pagination Disabled

[
    {
        "id": 1,
        "name": "John Doe",
        "email": "john@example.com",
    },
    {
        "id": 2,
        "name": "Forrest Gump",
        "email": "forrest@example.com",
    },
    //...
]
```

When Enabled the API will return collection along with its pagination data.

```yaml
// Pagination Enabled

{
    "data": [
        {
            "id": 1,
            "name": "John Doe",
            "email": "john@example.com",
        },
        {
            "id": 2,
            "name": "Forrest Gump",
            "email": "forrest@example.com",
        },
        //...
    ],
    "meta": {
        "pagination": {
            "total": 50,
            "per_page": 15,
            "from": 1,
            "to": 15,
            "current_page": 1,
            "last_page": 4,
            "path": "http://localhost:1337/api/users",
            "links": {
                "first": "http://localhost:1337/api/users?page=1",
                "last": "http://localhost:1337/api/users?page=4",
                "prev": null,
                "next": "http://localhost:1337/api/users?page=2"
            }
        }
    }
}
```

We will have to implement pagination in the Query Builder or ORM layer. Someone has implemented similar kind of package for Bookshelf.js ORM inspired by Laravel Eloquent ORM. Here is the link to it - https://github.com/Askedio/bookshelf-simplepaginate#readme

The link from the Laravel docs for Pagination section -
https://laravel.com/docs/8.x/eloquent-resources#pagination

JSON API standard reference:
https://jsonapi.org/format/#fetching-pagination
https://jsonapi.org/profiles/ethanresnick/cursor-pagination/#profile-intro

I'm looking forward and willing to contribute if this issue gets enough support.
