### ISSUE TITLE
after installation and build the strapi admin does not start

### ISSUE THREAD

**Issue by rafaumeu** [strapi/strapi#10944]
### Bug description

after installation and build strapi exits run with exit 0
### Steps to reproduce the behavior

1. yarn create strapi-app my-project --quickstart 
2. wait instalation done
3. cd my-project 
4. yarn develop

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.17.6
- NPM version: 6.14.15
- Strapi version: 3.6.8
- Database: tests quick install 
- Operating System: Linux Mint 20.1
            Kernel: Linux 5.4.0-84-generic
      Architecture: x86-64

### Additional context

the strapi doesn't work with either docker or npm, same error

https://user-images.githubusercontent.com/30784471/133006279-576097d8-2fdd-4291-96e4-849cc4756e16.mp4

https://user-images.githubusercontent.com/30784471/133006290-28a937c9-ebdc-4230-8ec7-45430e87c0c8.mp4

docker

https://user-images.githubusercontent.com/30784471/133007042-95fceee8-c616-4f40-ac82-6c9a3991d066.mp4

docker-compose.yaml
```

version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data

```
