### ISSUE TITLE
Found 4 circular dependencies!

### ISSUE THREAD

**Issue by rogwild** [strapi/strapi#11022]
Greetings!

I recently had a problem with GitHub Actions and the project on Strapi.
I used to run:
```
# check-backend-build.yaml
name: Check backend build
on:
  pull_request:
    branches:
      - develop
    paths:
      - app/**

jobs:
  check-backend-build:
    name: Checking the backend compilation capability
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Add bit registries
        run: yarn config set @bit:registry https://node.bit.dev
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install & Build
        run: yarn install && yarn build
      - run: echo 'Project is available for deployment'
```

And everything was fine, but now the following problem began to appear:

```
$ strapi build
Error while running command build: Could not load function /home/runner/work/dashboard-backend/dashboard-backend/app/config/functions/bootstrap.js: Class extends value undefined is not a constructor or null
```

Digging deeper, I found out that this is a signal of circulating dependencies and locally run
`npx madge --warning --circular --extensions js .`

Here's what I got:

```
✖  Found 4 circular dependencies!

1) .cache/admin/src/app.js > .cache/admin/src/containers/App/index.js > .cache/admin/src/containers/NotificationProvider/index.js > .cache/admin/src/containers/NotificationProvider/actions.js
2) .cache/plugins/strapi-plugin-content-manager/admin/src/components/FieldComponent/index.js > .cache/plugins/strapi-plugin-content-manager/admin/src/components/NonRepeatableComponent/index.js
3) .cache/plugins/strapi-plugin-content-manager/admin/src/components/FieldComponent/index.js > .cache/plugins/strapi-plugin-content-manager/admin/src/components/RepeatableComponent/index.js > .cache/plugins/strapi-plugin-content-manager/admin/src/components/RepeatableComponent/DraggedItem/index.js
4) .cache/plugins/strapi-plugin-content-type-builder/admin/src/components/List/index.js > .cache/plugins/strapi-plugin-content-type-builder/admin/src/components/ComponentList/index.js
```

Can you tell me what I need to do to be able to continue using GitHub Actions?
Is it possible to remove circulating dependencies explicitly?
