### ISSUE TITLE
[v4] Add a 3rd publicationState state just for Draft Articles

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#11350]
### Please describe your feature request

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [ ] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

Currently we have 2 different states for Draft & Publish:

- live: shows only published entries
- preview: shows published and draft entries

This request is to add a 3rd state which only shows drafts

- draft: shows only draft entries (this doesn't exist today)

### Why is it needed?

There is a use-case where you only want to pull the drafts and allow easy integration into the `strapi-sdk` as right now you have to use the `publicationState: "preview"` in addition to `published_at[null]: true`

### Suggested solution(s)

Add a 3rd publicationState called Draft which limits the response to only draft entries

### Related issue(s)/PR(s)

N/A
CC: @Stun3R

**Comment by petersg83** [comment]
Would it be only for the first level or all levels?

- If I have an **article (draft)** with a relation with an **author (draft)**. I query the article with `publicationState=draft`, do I see the populated author ?
- If I have an **article (draft)** with a relation with an **author (published)**. I query the article with `publicationState=draft`, do I see the populated author ?

**Comment by derrickmehaffy** [comment]
> Would it be only for the first level or all levels?
> 
> * If I have an **article (draft)** with a relation with an **author (draft)**. I query the article with `publicationState=draft`, do I see the populated author ?
> * If I have an **article (draft)** with a relation with an **author (published)**. I query the article with `publicationState=draft`, do I see the populated author ?

That is a good question, I would lean towards the first one but it really depends on the users use-case. :thinking: Maybe a config option to allow swapping logic

**Comment by Stun3R** [comment]
I agree with Derrick. It would he the first level but if a way of config this logic can be implemented that would be really nice

**Comment by Stun3R** [comment]
> `live` (only published content) and `preview` (all draft and published content) are applied for all levels. The logic would then be broken if it is only the first level for `draft`. Wdyt?

I think we didn't know it was apply for all level so if it's the case it would be the same for draft 👌🏻

**Comment by petersg83** [comment]
Ok I understand. Do you see a usecase to do it at all levels? It seems to me that the usecase is to have drafts for the first level and keep the published relations of those draft entries.

Here is an example of what would happen if we filter on every levels.
Does it make sense to not include Yves?
Does it make sense to have the information that French is in draft (Emma) but not that English is in draft too? (I ask this question because I believe that the idea of having `publicationState=draft` is to see what needs to be published, so you would need to see all drafts, even those that are related to a published content).
```
Article (draft)
  - title: 'Our trip to Strasbourg'
  - content: 'lorem ipsum'
  - categories:
    - Food (draft)
    - ❌Travel (published)
  - authors:
    - Emma (draft)
      - name: Emma
      - languages:
        - French (draft)
        - ❌Italian (published)
    - ❌Yves (published)
      - name: Yves
      - languages:
        - English (draft)
        - Arabic (published)
```
```
Article (draft)
  - title: 'Our trip to Strasbourg'
  - content: 'lorem ipsum'
  - categories:
    - Food (draft)
  - authors:
    - Emma (draft)
      - name: Emma
      - languages:
        - French (draft)
```

It seems to me that there is not really a usecase for `publicationState=draft`. Technically it is possible to implement it but it could mislead users I think. The usecase for them being almost all the time `publicationState=preview` + `published_at[null]=true` and not `publicationState=draft`.

What do you think?
