### ISSUE TITLE
Cannot access strapi in development mode

### ISSUE THREAD

**Issue by ari-motors-team** [strapi/strapi#12191]
### Describe the bug

Cannot access strapi in development mode on localhost, running `yarn develop` from within a docker container.
![image](https://user-images.githubusercontent.com/95754840/149338287-0a4aa8fd-b4f4-4886-9b90-ee6cb7c51719.png)

Here is the console info:
![image](https://user-images.githubusercontent.com/95754840/149339098-6dffccce-5a61-4777-b43c-47c9958927e9.png)

### Steps to reproduce the behavior

1. Setup strapi with docker
2. Run with `yarn develop`
4. Collection types cannot be changed

### Expected behavior

Runs in dev mode.

### Code snippets

docker-compose.yml
```yml
version: "3"
services:
  strapi:
    image: egahmad/strapi-docker
    command: yarn develop
    restart: always
    volumes:
      - ./strapi:/srv/app:z
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data:z
```

### System

- Node.js version: 16
- NPM version: 8.1.2
- Strapi version: 4.0.4
- Database: postgres
- Operating system: fedora
