### ISSUE TITLE
Unable to build Strapi with Yarn berry

### ISSUE THREAD

**Issue by iicdii** [strapi/strapi#12452]
### Describe the bug

You can't install Strapi with yarn berry.

### Steps to reproduce the behavior

1. `yarn create strapi-app my-project --quickstart`
2.

```bash
cd my-project
rm -rf .cache yarn.lock
yarn set version berry
yarn install
yarn build
```

### Expected behavior

Strapi should success to build with yarn berry.

### System

- Node.js version: v14.17.1
- NPM version: 8.4.1
- Strapi version: 4.0.7
- Database: SQLite
- Operating system: MacOS M1

### Additional context
When I tried to `yarn build`, it throws an error
```
Error: @strapi/admin tried to access object-assign, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: object-assign
Required by: @strapi/admin@npm:4.0.7
```

I declared required packages into `.yarnrc.yml` until every `it isn't declared in its dependencies` error disappeared
```yml
yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "@strapi/admin@*":
    dependencies:
      object-assign: "*"
      whatwg-fetch: "*"
      react-is: "*"
  "@strapi/babel-plugin-switch-ee-ce@*":
    dependencies:
      "@babel/template": "*"
      "reselect": "*"
      "resolve": "*"
```

And this new error appeared.
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'lodash/merge' in '/Users/username/Develop/strapi-serverless/.cache/admin/src'
```
