### ISSUE TITLE
Run Strapi v4 image on WSL leads to Error: spawn /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe ENOENT

### ISSUE THREAD

**Issue by sevbauer** [strapi/strapi#12479]
### Describe the bug

I create my own Strapi v4 docker image based on this tutorial: [https://blog.dehlin.dev/docker-with-strapi-v4](https://blog.dehlin.dev/docker-with-strapi-v4).
When I try to **run it in WSL with podman-compose**, I get the following error:

```
Error: spawn /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

Some research showed, that it might be caused by trying to open the browser on start. But I already tried to to set `autoOpen` of the Admin-config in `admin.js` to `false`. Also, I set `BROWSER=false` in the .env-file.

### Steps to reproduce the behavior

1. [Setup WSL on Windows](https://docs.microsoft.com/en-us/windows/wsl/install#install-your-linux-distribution-of-choice)
2. [Install podman](https://www.redhat.com/sysadmin/podman-windows-wsl2)
3. [Install podman-compose](https://techviewleo.com/how-to-manage-containers-with-podman-compose/)
4. Create a new strapi project
  a. Directly in WSL
  b. Or on Windows and cd into /mnt/c/...
5. Change `config/database.js` like below
5. Put the Dockerfile and docker-compose.yml from below into the strapi-project root
6. Add an `.env` file like below
7. Build the image with `podman build -t mystrapi:latest .`
8. Run `podman-compose up`

### Expected behavior

Strapi should start error-free in the docker-container and should be accessible with port 1337.

#### config/database.js

```
module.exports = ({ env }) => ({
  connection: {
    client: 'postgres',
    connection: {
      host: env('DATABASE_HOST', '127.0.0.1'),
      port: env.int('DATABASE_PORT', 5432),
      database: env('DATABASE_NAME', 'strapi'),
      user: env('DATABASE_USERNAME', ''),
      password: env('DATABASE_PASSWORD', ''),
    },
    useNullAsDefault: true,
  },
});
```

#### .env (Example)

```
DATABASE_HOST=localhost
DATABASE_PORT=5432
DATABASE_NAME=strapi
DATABASE_USERNAME=strapi
DATABASE_PASSWORD=strapi
```

#### Dockerfile

```
FROM node:16-slim
# Installing libvips-dev for sharp compatability
RUN apt-get -y update && apt-get -y install libvips-dev
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
WORKDIR /opt/app
COPY ./package.json ./
COPY ./yarn.lock ./
ENV PATH /opt/app/node_modules/.bin:$PATH
RUN yarn config set network-timeout 600000 -g
RUN yarn install
# WORKDIR /opt/app
COPY ./ .
RUN yarn build
EXPOSE 1337
CMD ["yarn", "develop"]
```

#### docker-compose.yml

```
version: '3'

networks:
  strapi-network:
    driver: bridge

services:
  strapi:
    container_name: strapi
    build: .
    env_file: .env
    image: mystrapi:latest
    networks:
      - strapi-network
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      BROWSER: false
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/app/package.json
      - ./yarn.lock:/opt/app/yarn.lock
      - ./.env:/opt/app/.env
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: bitnami/postgresql
    container_name: postgres
    env_file: .env
    networks:
      - strapi-network
    environment:
      POSTGRESQL_DATABASE: ${DATABASE_NAME}
      POSTGRESQL_USERNAME: ${DATABASE_USERNAME}
      POSTGRESQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres-volume:/bitnami/postgresql
    ports:
      - '5433:5432'
      
volumes:
  postgres-volume:
    external: false
```

### System

- Node.js version: v16.14.0
- YARN version: v1.22.17
- Strapi version: v4.0.6
- Database: PostgreSQL 14.1
- Operating system: Windows 10 Pro using WSL

### Additional context

Things I tried:
https://github.com/vuejs/vue-cli/issues/4125
https://stackoverflow.com/questions/52170312/spawn-cmd-exe-enoent-error-on-running-react-native-project
