### ISSUE TITLE
Warning: An error occured while requesting the API - using HTTPS and a Reverse Proxy (Traefik)

### ISSUE THREAD

**Issue by NKnuelle** [strapi/strapi#12908]
## Bug report
Error: "Warning: An error occurred while requesting the API" using Docker-Compose and Strapi (v4) behind Traefik as a reverse proxy.

### Describe the bug
I am using Docker-Compose to spin up Strapi and a PostgreSQL DB. Currently I am using Strapi in Development mode. I followed this guide https://blog.dehlin.dev/docker-with-strapi-v4 which is also promoted in this Thread: https://github.com/strapi/strapi-docker/issues/321. I made some small changes to use node and npm, not yarn.

Everything is working fine and Strapi is available with HTTPS under my subdomain. The error occurs if I click on the button to create my first admin user. Then the error message "Warning: An error occurred while requesting the API" occurs and nothing more. No logs, no additional errors.. What I found is, that the network tab in the dev tools shows the correct subdomain for nearly all requests but two requests are still using localhost (see screenshots)? This also leads to errors in the browser console. So somewhere "localhost" seems to be hard-wired?

### Steps to reproduce the behavior

1. Follow the guide on https://blog.dehlin.dev/docker-with-strapi-v4
2. Change the Dockerfile to my version below
3. Build the image
4. Create Docker-Compose.yml with my details below
5. Run the container
6. Try to create your first admin
7. Watch Browser dev tools / docker logs

### Expected behavior

Creating the first admin without problems.

### Screenshots

![grafik](https://user-images.githubusercontent.com/24235417/159442374-9bb9eacb-acc2-4ccd-a470-767bb8f6e762.png)

![grafik](https://user-images.githubusercontent.com/24235417/159442659-a9b5be8a-ea44-4726-9686-4d46c7ce8992.png)

![grafik](https://user-images.githubusercontent.com/24235417/159443165-6a350b1c-3030-4e77-9bed-c965820b675e.png)

### Code snippets

Dockerfile:
```
RUN apt-get update && apt-get install -y libvips-dev
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
WORKDIR /opt/
COPY ./package.json ./
COPY ./package-lock.json ./
ENV PATH /opt/node_modules/.bin:$PATH
RUN npm install
WORKDIR /opt/app
COPY ./ .
RUN npm build
EXPOSE 1337
CMD ["npm", "run", "develop"]
```
Docker-Compose.yml:
```
version: "3"
services:
  strapi:
    container_name: strapi
    build: .
    image: strapiv4:4.1.5
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: postgresDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    links:
      - postgresDB:postgresDB
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.lock
      - ./.env:/opt/app/.env
    ports:
      - "1337:1337"
    networks:
      - strapi
      - traefik-public
    depends_on:
      - postgresDB
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - traefik.http.routers.strapi-http.rule=Host(`my.subdomain.de`)
        - traefik.http.routers.strapi-http.entrypoints=http
        - traefik.http.routers.strapi-http.middlewares=https-redirect
        - "traefik.http.routers.strapi-https.rule=Host(`my.subdomain.de`)"
        - "traefik.http.routers.strapi-https.tls=true"
        - "traefik.http.routers.strapi-https.tls.certresolver=netcup"
        - "traefik.http.routers.strapi-https.entrypoints=https"
        - "traefik.http.services.strapi.loadbalancer.server.port=1337"


  postgresDB:
    image: postgres:12.0-alpine
    container_name: postgresDB
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - strapi

networks:
  strapi:
    name: Strapi
    driver: bridge
  traefik-public:
    external:
      true

```
config/server.js:
```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url : env('URL', 'https://my.subdomain.de'),
  app: {
    keys: env.array('APP_KEYS'),
  },
});
```

### System

- Node.js version: v14.19.1, because v16 is not officially supported according to the docs
- NPM version: 6.14.16
- Strapi version: v4
- Database: PostgreSQL
- Operating system: Ubuntu 20.04 LTS

### Already tried
- Adding url to the config/server.js
- rebuilding the image
- run npm build (after each change applied to configs)
- spin down / up the containers
