### ISSUE TITLE
Strapi AWS Deployment

### ISSUE THREAD

**Issue by nikhil-shrestha** [strapi/strapi#13161]
## Bug report

Link to the documentation page or resource
https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/amazon-aws.html

### Required System information
Node.js version: v14.19.1
Strapi version: 4.1.7

Deployed on AWS Elastic Beanstalk 

### Describe the bug
I have followed the instructions steps for step and was able to host the application to AWS Elastic Beanstalk, but when i visit the page ```http://example.com/admin```, to admin panel in the browser, it tries to hit ```http://localhost:1337/admin/project-type``` instead of trying to hit ```http://example.com/admin/project-type```. Also, followed the instructions steps for step multiple times and tried to deploy on EC2 same result

### Screenshots
![Screen Shot 2022-04-20 at 12 06 25 PM](https://user-images.githubusercontent.com/17779457/164163620-a1f01903-b1a4-4c8b-8c07-717fed936a09.png)
![Screen Shot 2022-04-20 at 12 06 37 PM](https://user-images.githubusercontent.com/17779457/164163637-9ba09d88-6a94-4012-a3c0-4ad061c8abb0.png)

### Code snippets

**buildspec.yml**
```
version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build:prod

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*" 
```

**Procfile**
> web: npm run start:prod

**package.json**
```
"scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi",
    "build:prod": "NODE_ENV=production npm run build --clean",
    "start:prod": "NODE_ENV=production npm start"
  },
```

### Additional context
Root cause: can't override ```STRAPI_ADMIN_BACKEND_URL```, so the admin build use default ```localhost:1337```.

**Note**
rebuild with production env didn't resolve the issue as mention in this forum
https://forum.strapi.io/t/strapi-4-0-desployed-admin-keep-call-to-http-localhost-1337-admin-project-type/15028/6
