### ISSUE TITLE
An error occurred while requesting the API

### ISSUE THREAD

**Issue by doums** [strapi/strapi#13420]
### Required System information

- Node.js version: v16.15.
- NPM version: 8.5.5
- Strapi version: 4.2.0-beta.2
- Database: mariadb
- Operating system: linux debian

Note that the generated project use TypeScript.

### Describe the bug

Hi, the problem occurs on a production env, after a prod deployment. When I hit the URL of the admin panel `sub.domain.stuff/admin` in the browser, I got a blank page, with an infinite purple loader, and a popup opens with the message 
> Warning: An error occurred while requesting the API

In the network inspector, all is green except two requests
```
GET http://localhost:1337/admin/project-type
GET http://localhost:1337/admin/init
```
In the console, there are some error logs
```
Content Security Policy: Parsing of 'script-src-attr' failed because the directive is unknown.
Content Security Policy: Page settings prevented an inline ("script-src") resource from loading.
Network Error -> trace https://pastebin.com/51VKJUv3
Content Security Policy: Page settings prevented a resource from loading at http://localhost:1337/admin/project-type ("connect-src").
Content Security Policy: Page settings prevented a resource from loading at http://localhost:1337/admin/init ("connect-src").
```

Note that on my local machine, the app works without any problem, even in a production mode (`NODE_ENV=production`) and running it with
```
npm run build
npm start
```

I deployed it using docker, and running it with the command `npm start` (aka `strapi start`) after a successful build.
This is my `Dockerfile`
```
FROM node:16-alpine
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /opt
COPY packages/back-strapi/ app/
WORKDIR /opt/app/
RUN npm ci
ENV PATH /opt/node_modules/.bin:$PATH

# build strapi app and start it
RUN npm run clean
RUN npm run build
RUN npm prune --production
EXPOSE 1337
CMD ["yarn", "start"]
```

and the `docker-compose.yml` I use for build

```
version: "3.9"
services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: packages/back-strapi/.docker/Dockerfile
    image: custom-strapi
    restart: unless-stopped
    env_file: .env
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapi-db

  strapi-proxy:
    container_name: strapi-proxy
    image: caddy:alpine
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./packages/back-strapi/.caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./packages/back-strapi/.caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - strapi
```

As you can see for production env, I reverse proxy using Caddy, this is the `Caddyfile` I use

```
{$DOMAIN} {
        # compress responses to improve performances
        encode zstd gzip

        log {
                format console
        }

        # host is strapi since the app run in a docker container, service = `strapi`
        reverse_proxy strapi:1337
}
```

Finally, this is my `config/server.ts`

```
export default ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  app: {
    keys: env.array('APP_KEYS'),
  },
  url: env('STRAPI_URL'), // my sub.domain
});
```

### Expected behavior

The admin panel should just work as expected. 

### Screenshots

![image](https://user-images.githubusercontent.com/6359431/171059933-00672c55-aa60-4d47-94f8-2f8b071b01a1.png)

### Additional context

There is no additional

**Comment by derrickmehaffy** [comment]
> I think there is a problem with these requests since the host should be my domain sub.domain.stuff/admin and not localhost:1337.

> `url: env('STRAPI_URL'), // my sub.domain`

You don't actually set the var anywhere, it needs to be set when you run `npm run build`

**Comment by doums** [comment]
For the sake of clarity, I omitted the `environment` property in docker-compose but the `STRAPI_URL` is sets here correctly
```
    environment:
      NODE_ENV: ${STRAPI_NODE_ENV}
      HOST: ${STRAPI_HOST}
      PORT: ${STRAPI_PORT}
      STRAPI_URL: ${STRAPI_URL}
      # ...
```
So if I'm right, the STRAPI_URL is set during the build of Strapi. Plus when the app strat, I see the log with the right endpoint
```
┌────────────────────────────────────┐
│ https://sub.domain.ch/admin                                                                                   │
└────────────────────────────────────┘
```
