### ISSUE TITLE
Error connecting to the Mongo database. Unescaped slash in userinfo section

### ISSUE THREAD

**Issue by a-hardin** [strapi/strapi#13671]
- Node.js version: 14.16.0
- Yarn version: 1.22.5
- Strapi version: 3.6.8
- Database: MongoDB
- Database Host: cloud.mongodb.com
- Operating system: Linux
- Environment: Local/Docker
- Strapi Image: strapi/strapi:3.6.8

### Describe the bug

When trying to spin up the container using `docker-compose up` I get the following error: 
> error Error connecting to the Mongo database. Unescaped slash in userinfo section
My username and password are alphanumeric and the only special characters are `_` (underscore)

### Steps to reproduce the behavior

1. Go to terminal
2. navigate to the project directory
3. run docker-compose up
4. see error in terminal 

### Expected behavior

Strapi to connect to the mongo database without error

### Screenshots

Project folder structure
![Screenshot from 2022-07-01 09-59-32](https://user-images.githubusercontent.com/25305805/176919687-76ba66bc-c26d-48c0-a81a-2b12dd2c9093.png)

### Code snippets

docker-compose.yml
```
version: "3"

services:
  strapiexample:
    image: strapi/strapi:3.6.8
    container_name: strapicms
    restart: unless-stopped
    env_file: .env
    environment:
      APP_NAME: strapi-cms
      DATABASE_CLIENT: mongo
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
```

app/config/database.js
```
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'mongoose',
      settings: {
        host: env('DATABASE_URL'),
      },
      options: {
        authenticationDatabase: env('AUTHENTICATION_DATABASE', null),
        ssl: env.bool('DATABASE_SSL', false),
      },
    },
  },
});
```

.env
The username, passwords, and database are similar
```
DATABASE_URL=mongodb+srv://aaa_aa_2222:aaa_aaaa_1111@secret.asd38.mongodb.net/fakedb?retryWrites=true&w=majority
```
