### ISSUE TITLE
Trouble using environment variables with url in server.js

### ISSUE THREAD

**Issue by edleeman17** [strapi/strapi#13877]
### Required System information
- Node.js version: v14.16.0
- NPM version: v6.14.11
- Strapi version: v4.1.12
- Database: postgres
- Operating system: Linux/Docker

### Describe the bug

I'm having issues trying to set the `url` parameter in the `server.js` file. It feels to be inconsistent and I can't work out why it may not be working.

First off, I am trying to run this locally, using `http://localhost:8080/backend` as the strapi backend e.g `http://localhost:8080/backend/admin` will take me to the login page.

Here is a working example that I have:

``` javascript
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: 'http://localhost:8080/backend',
  app: {
    keys: env.array('APP_KEYS'),
  },
});
```

As you can see, this works:
![image](https://user-images.githubusercontent.com/61695425/181462215-92e1e751-6be6-4551-8165-3192059fb494.png)

Issue is, I want to be able to use an environment variable. (I'm using example.com as the fallback just to prove my next issue)

``` javascript
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('STRAPI_BACKEND_URL','http://example.com/backend'),
  app: {
    keys: env.array('APP_KEYS'),
  },
});
```

I then run `docker-compose build && docker-compose up -d`

I then get the usual API error

![image](https://user-images.githubusercontent.com/61695425/181463507-e748f6ca-cbb7-421d-b7d0-c65f74bebe81.png)

As it is falling back to the `example.com` domain.

![image](https://user-images.githubusercontent.com/61695425/181463650-ad5f1215-e92e-4cab-9db3-8fac6697bba9.png)

However, if I read the environment variables from the strapi project...

![image](https://user-images.githubusercontent.com/61695425/181463855-609de4cf-9c98-4bbc-ae5e-ec37133388c7.png)

The value is there.

I don't understand why the environment variable isn't applying.

I tried some other scenarios, I'll list them below..

`url: process.env.STRAPI_BACKEND_URL`  [DOESNT WORK]
```url: `${process.env.STRAPI_BACKEND_URL}` ``` [DOESNT WORK]

`url: env('anything','http://localhost:8080/backend')` [WORKS]
`url: http://localhost:8080/backend` [WORKS]
`url: 'http://localhost:8080/backend'` [WORKS]

It seems that any time I use an environment variable, it doesn't work. Even though `HOST` and `PORT` are both fine. The `STRAPI_BACKEND_URL` environment variable is in the same file as the `HOST` and `PORT` configuration.

---

My environment is all within Docker, using a `docker-compose.yml` file to spin everything up. Please find my configuration below...

Strapi dockerfile
```
FROM strapi/base

WORKDIR /app

COPY ./package.json ./
# COPY ./package-lock.json ./

RUN npm install

COPY . .

ENV NODE_ENV production

RUN npm run build

EXPOSE 1337

CMD ["npm", "start"]
```

Global `docker-compose.yml`

``` yaml
version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - storefront
      - storefront-functions
      - strapi
    restart: unless-stopped
  storefront:
    build: 
      context: ./storefront
      args:
        STRIPE_PUBLIC_KEY: $STRIPE_PUBLIC_KEY
        STRIPE_CONNECTED_ACCOUNT_ID: $STRIPE_CONNECTED_ACCOUNT_ID
        STOREFRONT_FUNCTIONS_URL: $STOREFRONT_FUNCTIONS_URL
        STRAPI_BACKEND_URL: $STRAPI_BACKEND_URL
        STOREFRONT_URL: $STOREFRONT_URL
        SITE: $SITE
    env_file:
    - production.env
    depends_on:
      - strapi
    restart: unless-stopped
  strapi:
    env_file:
    - production.env
    - strapi-backend.env
    - database.env
    build: ./strapi-backend
    depends_on:
      - db
    restart: unless-stopped
  storefront-functions:
    build: ./storefront-functions
    env_file:
      - production.env
      - storefront-functions.env
    depends_on:
      - storefront
    restart: unless-stopped
  chartbrewdb:
    image: mysql:5.7
    restart: always
    env_file:
      - chartbrew.env
    volumes:
      - ./chartbrew-db:/var/lib/mysql
  chartbrew:
    image: razvanilin/chartbrew
    restart: always
    env_file:
      - chartbrew.env
    depends_on:
      - chartbrewdb
  db:
    image: postgres:14.1-alpine
    env_file:
      - production.env
      - database.env
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped
```

nginx config

```
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        proxy_pass http://storefront;
    }

    location /chart-api {
        proxy_pass http://chartbrew:4019;
        rewrite ^/chart-api/?(.*)$ /$1 break;
    }

    location /charts {
        proxy_set_header HOST $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        proxy_pass http://chartbrew:3000;
    }

    location /functions {
        proxy_pass http://storefront-functions:5000;
        rewrite ^/functions/?(.*)$ /$1 break;
    }

    location /backend {
        proxy_pass http://strapi:1337;
        rewrite ^/backend/?(.*)$ /$1 break;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
    }
}
```

Please let me know if you need anything else from me, really appreciate your time on this!

Many thanks
