### ISSUE TITLE
Strapi crashes locally after creating content type

### ISSUE THREAD

**Issue by donnierisk** [strapi/strapi#14237]
### Required System information

- Node.js version: v16.17.0
- NPM version: 8.15.0
- Strapi version: latest
- Database: Dockerised PostgreSQL
- Operating system: Mac OS

### Describe the bug

When I run Strapi locally first time using "npm run develop" it works fine. I register, then as soon as I click "save" after creating a new content type with a field, Strapi crashes.

My Strapi config looks like this:
<img width="478" alt="Screenshot 2022-08-28 at 14 54 40" src="https://user-images.githubusercontent.com/17927429/187075081-e2857ea5-a9dd-4174-a263-cc2be502cdc6.png">
My PostgreSQL docker-compose file looks like this:
<img width="522" alt="Screenshot 2022-08-28 at 14 55 02" src="https://user-images.githubusercontent.com/17927429/187075090-7e2fd4a4-afc4-45e0-a669-3e0e570d62aa.png">

When I hit save it runs until here, then I get 45 TypeScript errors:
<img width="844" alt="Screenshot 2022-08-28 at 14 56 37" src="https://user-images.githubusercontent.com/17927429/187075151-e4ef9f67-273e-4746-8ecd-7c7ad11d4256.png">
<img width="986" alt="Screenshot 2022-08-28 at 14 57 05" src="https://user-images.githubusercontent.com/17927429/187075166-1c6ccbb0-69de-4a91-9492-b536ed4f3a50.png">

### Steps to reproduce the behavior

1. Install local Strapi, 
2. Run PostgreSQL docker locally
3. Connect to database
4. Register account
5. Create new content type + a field and save it

### Expected behavior

The Strapi app saves the content type and I can continue working.

### Code snippets
db-docker-compose.yml:
```
version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bbs
    ports:
      - '5433:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    
volumes:
  db:
    driver: local
```

### Additional context
The content type does seem to get created within the src/api folder. As soon as I delete the content there the Strapi app can run again using npm run develop.
