### ISSUE TITLE
 My data were deleted from Postgres after some time.

### ISSUE THREAD

**Issue by zprx** [strapi/strapi#14779]
### Required System information

- Node.js version: v16.13.0
- Strapi version: v4.4.1
- Database: PostgreSQL
- Operating system: Linux

### Describe the bug

Second time in one week data were deleted from PostgreSQL by itself.
I have not done any update, and I today when I was not able to build project, I found out that database empty, and all data dropped. It's second case in one week, what is going on , how I can fix this?

### Code snippets

**_database.js_**
```const fs = require('fs');
const path = require('path');

export default ({ env }) => {
  return {
    connection: {
      client: 'postgres',
      connection: {
        host: env('DATABASE_HOST', ''),
        port: env.int('DATABASE_PORT', 25060),
        database: env('DATABASE_NAME', ''),
        user: env('DATABASE_USERNAME', ''),
        password: env('DATABASE_PASSWORD', ''),
        ssl: {
          ca: env('DATABASE_SSL', fs.readFileSync(`${path.resolve('./')}/config/ca.crt`).toString()),
        },
      },
    },
  }
};
```

**_Dockerfile_** 
```
FROM node:16-alpine3.15

# Create app directory
WORKDIR /usr/src/app

COPY . ./
RUN rm -rf ./node_modules
RUN npm install
RUN npm install --save @strapi/strapi
RUN npm run build
EXPOSE 1337
```
**_DOCKER-COMPOSE_**
```
version: "3.9"
services:
  content-api_dev:
    restart: always
    env_file:
    - .env
    image: {ACCOOUNT}cms-api:latest
    command: npm run start
    ports:
      - "2000:1337"
```

P.S.: All credentials were removed for secure reason 

I am using digitalocean cloud database service.
