### ISSUE TITLE
Cannot upload files to asset store in Dockerized Strapi App - "Files are empty" error

### ISSUE THREAD

**Issue by rasmus-rudling** [strapi/strapi#14890]
### Required System information

- Node.js version: 16(-alpine)
- Docker version: 20.10.17
- NPM version: 8.19.2
- Yarn version: 1.22.19
- Strapi version: 4.4.1
- Database: Postgres
- Operating system: linux/amd64

### Describe the bug

After following the ["Running Strapi in a Docker container"-guide](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/installation/docker.html) I've ended up with the following configuration:

```dockerfile
# [Dockerfile.dev]

FROM node:16-alpine
RUN apk update && apk add  build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt

COPY ./packages/cms/package.json .
COPY yarn.lock .

ENV PATH /opt/node_modules/.bin:$PATH
RUN yarn config set network-timeout 600000 -g && yarn install
WORKDIR /opt/app

COPY ./packages/cms .

EXPOSE 1337

CMD ["yarn", "dev"]
```

```yaml
# [compose.dev.yaml]

version: '3'

services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: ./packages/cms/Dockerfile.dev
    image: strapi:latest
    restart: unless-stopped
    env_file: ./packages/cms/.env.docker
    volumes:
      - ./packages/cms/config:/opt/app/config
      - ./packages/cms/src:/opt/app/src
      - ./packages/cms/package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./packages/cms/.env:/opt/app/.env
      - ./packages/cms/public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - strapi
    depends_on:
      - strapiDB
      
  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: ./packages/cms/.env.docker
    image: postgres:12.0-alpine
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
    ports:
      - '5432:5432'
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
```

I start the application by running `docker compose -f compose.dev.yaml up`.

Everything is working as I expect except for uploading files. When I try to add a new asset, it first seems as if the asset gets uploaded to the Strapi react client as expected as seen in the screenshot below
![image](https://user-images.githubusercontent.com/32018604/202126750-a2071616-e74c-4225-8209-1d95567915e9.png)

However, when I press "Upload 1 asset to the library" I get the following error:

![image](https://user-images.githubusercontent.com/32018604/202126994-4a6fed70-6675-45e5-9209-e5a69f631af9.png)
-
![image](https://user-images.githubusercontent.com/32018604/202127248-4bf58248-f182-464d-9fe1-9621c7346fac.png)
-
![image](https://user-images.githubusercontent.com/32018604/202127319-131bb440-58e5-4c2c-933b-4caf0ab416da.png)
-
![image](https://user-images.githubusercontent.com/32018604/202127430-b0e351c4-485f-4da0-b8ef-e662781c04b3.png)

**Note:** When running strapi locally (instead of via `docker compose`) everything with the file uploading is working.

Any ideas what could've gone wrong here?
