### ISSUE TITLE
It's not possible to override database.js in config/env/<environment>/database.js

### ISSUE THREAD

**Issue by zentavr** [strapi/strapi#15667]
### Required System information

- Node.js version: 14.21.2
- NPM version: 6.14.17
- Strapi version: 4.6.0
- Operating system: linux

### Describe the bug

As a developer I would like to set up my custom configuration and test it on a separate DB dump. In order to achieve this, I created pgdump, created my custom NODE_ENV and put the values inside `config/env/myfeature/database.js`. At the same time we have the default `config/database.js` which uses sqlite by default.

The doc says that during the app initialization the configuration merge happens, so everything what is in `config/env/myfeature/*.js` overrides what is in `config/*.js`.

```shell
/srv/app/config/env/production $ cat ../../database.js
const path = require('path');

module.exports = ({ env }) => ({
  connection: {
    client: 'sqlite',
    connection: {
      filename: path.join(__dirname, '..', env('DATABASE_FILENAME', '.tmp/data.db')),
    },
    useNullAsDefault: true,
  },
});

/srv/app/config/env/production $ cat database.js
const path = require('path');

module.exports = ({ env }) => ({
  connection: {
    client: 'postgres',
    connection: {
      host: env('DATABASE_HOST', 'localhost'),
      port: env.int('DATABASE_PORT', 5432),
      database: env('DATABASE_NAME', 'strapi'),
      user: env('DATABASE_USERNAME', 'strapi'),
      password: env('DATABASE_PASSWORD', 'strapi'),
      ssl: env.bool('DATABASE_SSL', false),

    },

  },
});

/srv/app/config/env/production $ ls -la
total 12
drwxrwsrwx    3 root     wifimap       4096 Feb  1 15:36 .
drwxr-xr-x    3 root     root          4096 Feb  1 15:27 ..
drwxr-sr-x    2 root     wifimap       4096 Feb  1 15:36 ..2023_02_01_15_36_34.603198481
lrwxrwxrwx    1 root     wifimap         31 Feb  1 15:36 ..data -> ..2023_02_01_15_36_34.603198481
lrwxrwxrwx    1 root     wifimap         18 Feb  1 15:26 database.js -> ..data/database.js
lrwxrwxrwx    1 root     wifimap         17 Feb  1 15:26 plugins.js -> ..data/plugins.js
lrwxrwxrwx    1 root     wifimap         16 Feb  1 15:26 server.js -> ..data/server.js
```

When application starts, it says it uses `sqlite`.

What might be the issue? Could it be because `/srv/app/config/env/production/database.js` the symlink in fact? We run it as a Pod in K8S cluster and actually the config appears from the k8s configmap.

**Comment by zentavr** [comment]
Seems like relative to #11399

**Comment by zentavr** [comment]
I'd tried to override `server.js` (to change port) and had the same case.

**Comment by zentavr** [comment]
It looks like the issue is here: https://github.com/strapi/strapi/blame/main/packages/core/strapi/lib/core/app-configuration/config-loader.js#L14

When the configuration file is a symlink to something else, it's not get considered as a valid file.

I use K8S configmap and those files are symlinks actually.

```
/srv/app/config # tree -a
.
├── admin.js
├── api.js
├── database.js
├── env
│   ├── .tmp
│   │   └── hello-override.db
│   └── production
│       ├── ..2023_02_01_20_30_30.1827649770
│       │   ├── ..data -> ..data
│       │   ├── database.js
│       │   └── server.js
│       ├── ..data -> ..2023_02_01_20_30_30.1827649770
│       ├── database.js -> ..data/database.js
│       └── server.js -> ..data/server.js
├── middlewares.js
├── plugins.js
└── server.js
```

**Comment by zentavr** [comment]
The workaround for k8s pod + configmap would be something like this:
```yaml
apiVersion: v1
kind: Pod
metadata:
   ...skipped...
spec:
  containers:
    - env:
          ...skipped...
      volumeMounts:
      - mountPath: /srv/app/public/uploads
        name: strapi-volume-claim
      - mountPath: /srv/app/config/env/production/server.js
        name: strapi-config-environment-js
        subPath: server.js
      - mountPath: /srv/app/config/env/production/database.js
        name: strapi-config-environment-js
        subPath: database.js
  volumes:
    - configMap:
      defaultMode: 420
      name: strapi-config-js
    name: strapi-config-environment-js
```
