### ISSUE TITLE
Blank admin panel after installing @strapi/provider-upload-aws-s3

### ISSUE THREAD

**Issue by milad2golnia** [strapi/strapi#16136]
### Required System information

- Node.js version: v16.19.0
- NPM version: 8.19.3
- Strapi version: 4.5.6
- Database: PostgreSQL
- Operating system: Linux Alpine (Output of uname: `Linux 3c473f9315ba 5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023 x86_64 Linux`)
- Is your project Javascript or Typescript: Typescript

### Describe the bug
When I install the `@strapi/provider-upload-aws-s3` package and without any other configuration and changes, I restart the docker and I see that I get an empty admin panel in browser. I'm really confused because installation process just changes `package.json` file.

Installation command:
```
npm i @strapi/provider-upload-aws-s3
```

Server logs doesn't complain about anything:
```
Welcome back!
To manage your project 🚀, go to the administration panel at:
http://localhost:1337/admin

To access the server ⚡, go to:
http://localhost:1337

[2023-03-19 12:48:14.602] http: GET /admin (19 ms) 200
[2023-03-19 12:48:15.178] http: GET /admin/runtime~main.02d42a1b.js (11 ms) 200
[2023-03-19 12:48:15.191] http: GET /admin/main.0a7c6639.js (2 ms) 200
[2023-03-19 12:48:20.243] http: GET /admin/project-type (4 ms) 200
[2023-03-19 12:48:20.620] http: GET /ckeditor5/ckeditor-config (2 ms) 200
[2023-03-19 12:48:20.673] http: GET /admin/email-translation-fr-json.03765a26.chunk.js (2 ms) 200
[2023-03-19 12:48:20.900] http: POST /admin/renew-token (14 ms) 200
[2023-03-19 12:48:20.908] http: GET /admin/init (4 ms) 200
[2023-03-19 12:48:21.409] http: GET /admin/telemetry-properties (61 ms) 200
[2023-03-19 12:48:21.570] http: GET /admin/Admin-authenticatedApp.012b8bdd.chunk.js (2 ms) 200
[2023-03-19 12:48:21.822] http: GET /admin/information (42 ms) 200
[2023-03-19 12:48:21.870] http: GET /admin/users/me/permissions (85 ms) 200
[2023-03-19 12:48:21.897] http: GET /admin/users/me (47 ms) 200
[2023-03-19 12:48:22.025] http: GET /i18n/locales (37 ms) 200
[2023-03-19 12:48:22.206] http: GET /admin/70674f63fc3904c20de0.svg (3 ms) 200
[2023-03-19 12:48:31.979] http: GET /ckeditor5/ckeditor-config (1 ms) 200
^C
```

### Steps to reproduce the behavior

1. I created project using:
```
$ npx create-strapi-app projectName --ts --dbclient=postgres --dbhost=strapiPostgres --dbport=5432 --dbname=projectName --dbusername=strapi --dbpassword=somepassword --dbforce
```
2. I installed `graphql` plugin for strapi.
3. I installed `ckeditor5` plugin for strapi.
4. The content of Dockerfile:
```
# path: ./Dockerfile

FROM node:16-alpine
# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
WORKDIR /opt/
ENV PATH /opt/node_modules/.bin:/opt/projectName/node_modules/.bin:$PATH
COPY projectName/package.json ./projectName/package.json
WORKDIR /opt/projectName
RUN npm i 
COPY ./projectName .
COPY ./projectName/.env.example ./.env
RUN npm run build
RUN ls -la
EXPOSE 1337
ENV APP_KEYS=5a7bef43-3994-41bb-ac31-3601c9977bbe,31a54b7b-ca1c-42e1-823f-687c78be8a6c
CMD ["npm", "run", "develop"]
```
5. The content of `docker-compose.yml` file:
```
version: '3'


services:
  ngx:
    container_name: ngx
    image: "nginx:1-alpine"
    restart: "always"
    ports:
      - 80:80
      - 443:443
      - '9000:9000'
      - '9001:9001'
    depends_on:
      - strapi
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt:ro
  strapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: strapi
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_NAME=projectName
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=somepassword
    volumes:
      - ./projectName/config:/opt/projectName/config
      - ./projectName/src:/opt/projectName/src
      - ./projectName/package.json:/opt/projectName/package.json
      # - ./projectName/.env:/opt/projectName/.env
      - ./projectName/public/uploads:/opt/projectName/public/uploads
    ports:
      - '1337:1337'
    depends_on:
      - postgres
  postgres:
    container_name: strapiPostgres
    image: postgres:15.1
    environment:
      - POSTGRES_DB=projectName
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=somepassword
    volumes:
      - /media/db:/var/lib/postgresql/data    
volumes:
  miniodata:
```
6. Everything is working.
7. install `@strapi/provider-upload-aws-s3` by running `npm i @strapi/provider-upload-aws-s3` and restart docker.
8. Go to `https://mydomainname/admin`. and get a blank page.
### Expected behavior
Hence installing `@strapi/provider-upload-aws-s3` just changes `package.json` I expect no changes after installing `@strapi/provider-upload-aws-s3` and I expect to get admin panel as before.

### Additional context
Logo and Title of page are loaded but itself is not displayed.
Inspecting admin panel page in browser and new errors which was not available before running this command:
```
TypeError: Property descriptor must be an object, got undefined
    s http://167.235.228.224:1337/admin/3327.a039ba5f.chunk.js:279
    il http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    ra http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    Wr http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    wt http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    Xe http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    kc http://167.235.228.224:1337/admin/main.0a7c6639.js:1192
    eu http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    unstable_runWithPriority http://167.235.228.224:1337/admin/main.0a7c6639.js:1219
    Ca http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    eu http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    gs http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    Ll http://167.235.228.224:1337/admin/main.0a7c6639.js:1192
    we http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    P http://167.235.228.224:1337/admin/admin-app.419df777.chunk.js:68
    _ http://167.235.228.224:1337/admin/admin-app.419df777.chunk.js:68
main.0a7c6639.js:1192:69
TypeError: Property descriptor must be an object, got undefined
    s http://167.235.228.224:1337/admin/3327.a039ba5f.chunk.js:279
    il http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    ra http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    Wr http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    wt http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    Xe http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    kc http://167.235.228.224:1337/admin/main.0a7c6639.js:1192
    eu http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    unstable_runWithPriority http://167.235.228.224:1337/admin/main.0a7c6639.js:1219
    Ca http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    eu http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    gs http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    Ll http://167.235.228.224:1337/admin/main.0a7c6639.js:1192
    we http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    P http://167.235.228.224:1337/admin/admin-app.419df777.chunk.js:68
    _ http://167.235.228.224:1337/admin/admin-app.419df777.chunk.js:68
main.0a7c6639.js:1192:69
TypeError: Property descriptor must be an object, got undefined
    s http://167.235.228.224:1337/admin/3327.a039ba5f.chunk.js:279
    il http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    ra http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    Wr http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    wt http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    Xe http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    kc http://167.235.228.224:1337/admin/main.0a7c6639.js:1192
    eu http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    unstable_runWithPriority http://167.235.228.224:1337/admin/main.0a7c6639.js:1219
    Ca http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    eu http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    gs http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    Ll http://167.235.228.224:1337/admin/main.0a7c6639.js:1192
    we http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    P http://167.235.228.224:1337/admin/admin-app.419df777.chunk.js:68
    _ http://167.235.228.224:1337/admin/admin-app.419df777.chunk.js:68
main.0a7c6639.js:1192:69
Uncaught (in promise) TypeError: Property descriptor must be an object, got undefined
    s http://167.235.228.224:1337/admin/3327.a039ba5f.chunk.js:279
    il http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    ra http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    Wr http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    wt http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    Xe http://167.235.228.224:1337/admin/main.0a7c6639.js:1194
    kc http://167.235.228.224:1337/admin/main.0a7c6639.js:1192
    eu http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    unstable_runWithPriority http://167.235.228.224:1337/admin/main.0a7c6639.js:1219
    Ca http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    eu http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    gs http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    Ll http://167.235.228.224:1337/admin/main.0a7c6639.js:1192
    we http://167.235.228.224:1337/admin/main.0a7c6639.js:1190
    P http://167.235.228.224:1337/admin/admin-app.419df777.chunk.js:68
    _ http://167.235.228.224:1337/admin/admin-app.419df777.chunk.js:68
3327.a039ba5f.chunk.js:279:10045
```

Content of `package.json`:
```
{
  "name": "projectName",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.3",
    "@strapi/plugin-graphql": "^4.5.6",
    "@strapi/plugin-i18n": "4.5.6",
    "@strapi/plugin-users-permissions": "4.5.6",
    "@strapi/provider-upload-aws-s3": "^4.8.2",
    "@strapi/strapi": "4.5.6",
    "pg": "8.6.0"
  },
  "workspaces": [
    "./src/plugins/strapi-plugin-ckeditor"
  ],
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "6b1319c5-8073-4c8a-ac5b-0a3acf44b5c3"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}

```
