### ISSUE TITLE
Wrong relation when clicking inside a record but ok when clicking on the index

### ISSUE THREAD

**Issue by redenm** [strapi/strapi#16260]
### Required System information

- Node.js version: 18
- NPM version: 9.4
- Strapi version: 4.6.2
- Database: Postgres
- Operating system: Ubuntu
- Is your project Javascript or Typescript: JS

### Describe the bug

I have a Navbar Menu collection, with fields of name (text), parent (hasMany Navbar Menus), children (belongsToMany Navbar Menus). It's a self relation. I think children is automatically created by Strapi. Anyway, I think it's better to understand this when there's a steps to reproduce. I also attached video. :)

### Steps to reproduce the behavior

1. Go to Collection Type > Navbar Menu edit a Record, the Children field is correct. But,
2. Clicking its Children will show you wrong relation. Wrong parent and wrong children.

### Expected behavior

When I go to Collection Type > Navbar Mane edit a record, I will see its children and parent (if there are any). This is correct.

When I click the Children (inside editing record) I should see its parent correctly. Same with its parent, when I click it, it should list all its children correctly

### Screenshots

1. So I'm in Navbar Menu collection, I clicked a parent named "Services". As we can see, it is loading its children correctly.
2. I click its children named "Private Jet Charter", it has children. It supposed to be a child, and I'm expecting a Parent but we can't see it.
3. I returned to Navbar Menu collection, search the record "Private Jet Charter", relation is correct, I only saw parent which is Services.
4. I then clicked Services, and no children, parent is Services but we're on Services. It should have parent but has children.

Here's a video https://user-images.githubusercontent.com/122326760/229040088-ee0374cf-3077-4813-84ad-41e885c818a1.mp4

If it looks confusing, I'm hitting back button on my mouse.

### 

Code snippets

The code I'm using is exactly what's on Strapi version 4.6.2

### Additional context

If this is not a bug, just let me know how can I fix it. :)

**Comment by derrickmehaffy** [comment]
Hey @redenm I wasn't able to reproduce this but could you try upgrading up to v4.9.0 and see if that helps at all, there have been a lot of fixes between v4.6.2 and v4.9.0.

**Comment by redenm** [comment]
All right, I'll upgrade the Strapi version and provide an update on this thread later.

**Comment by redenm** [comment]
UPDATE: This is indeed not reproducible. I tried using a fresh strapi version and it worked with no problems.

I forgot to say that I'm running Strapi on docker. I think that causes the problem. Node js works just fine. Here's my docker-compose file:

```yaml
version: "3"
services:
  app:
    container_name: strapi-app
    image: node:18
    volumes:
      - ./source:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "2000:1337"
    depends_on:
      - db
    command: >
      sh -c "npm install && npm run develop"
  db:
    container_name: strapi-db
    restart: always
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapiuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
```

**Comment by derrickmehaffy** [comment]
Sounds good @redenm I'll go ahead and close but if you do find a way to reproduce let us know!

**Comment by redenm** [comment]
Hello @derrickmehaffy I have reproduced this error. I think we might re-open this thread? I think the error is when Strapi is inside docker. For some reason, it behaves like that. But when it is running on Node, it works fine. Here's a short video:

https://user-images.githubusercontent.com/122326760/229621611-4b39c0a5-f647-49b8-a482-aca7c06b6ead.mp4

---

Again, same issue.

1. Create a Collection called "Navbar Menus"
2. Create the first content for Navbar Menu called "Services"
3. I forgot to add `isParent` so I edited the collection and add that boolean field
4. Edit "Services" and set `isParent` to `true`
5. Add a second content  called "Private Jet Charter" with "Services" as its parent
    5.1. Set `isParent` to `false`
    5.2. Hit publish
    5.3. Clicked Services _(we are still on the same page)_
    5.4. We are now on "Services" edit page, Relation is correct. Children is showing "Private Jet Charter"
    5.5. Clicked the "Private Jet Charter" now, relation is incorrect. It is showing a "Private Jet Charter" children even when we are inside that page, I should see "Services" as its parent. But it's missing.
6.  Clicked "Navbar Menu" _(I'm going back to index)_
7. Clicked Services - Relation is correct, children is showing "Private Jet Charter"
    7.1. Clicked it _("Private Jet Charter")_ relation is incorrect.

Same issues I have filed 4 days ago. But that was running on Docker, too inside Ubuntu. This video runs on WSL2, windows 11. I have replaced it with `Strapi 4.9.0 + Mysql`. Not sure if this bug cause by `Strapi 4.6.2 + Postgres` or `Strapi + Docker` because I have tried also with latest version and I can also reproduce the same error. Again, when I'm just using Ubuntu + node, it works perfect.

Attaching the exact copy, I have uploaded this to google drive because it's too big. Not sure if Github will allow me to upload it. https://drive.google.com/file/d/1nPkUMrpYRZJ9jCANUtQQ8E1gbjDYiPJ6/view?usp=sharing folder is named `x` for some reason 😁 

I'm happy to contribute to Strapi, anything else you need to know, just reply to this thread.

Thanks!

```yaml
version: "3"
services:
  app:
    container_name: strapi-app
    image: node:18
    volumes:
      - ./source:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "2000:1337"
    depends_on:
      - db
    command: >
      sh -c "npm install && npm run build && npm run develop"
  db:
    container_name: strapi-db
    restart: always
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
```
