### ISSUE TITLE
Unable to run Strapi behind Traefik

### ISSUE THREAD

**Issue by dexpetkovic** [strapi/strapi#16309]
### Required System information

- Node.js version: 18.15.0
- NPM version: 9.5.0
- Strapi version: 4.9.0
- Database: postgres
- Operating system: node:16.20.0-alpine3.17
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When running Strapi behind Traefik in subdirectory configuration, the admin CMS fails to start with error message:
```
Warning:

An error occurred while requesting the API
```

and the console shows
```
main.ca23e32b.js:441 TypeError: Cannot read properties of undefined (reading 'isEE')
    at main.ca23e32b.js:441:40688
```

### Steps to reproduce the behavior

1. Modify `config/server.ts` and add the below to the config object:
```
  url: "/cms",
  proxy: true,
```
2. Traefik routing rule is `traefik.http.routers.strapi-cms.rule: Host(`${BASE_HOST}`) && PathPrefix(`/cms`)`
3. Dockerfile.dev
```
FROM node:18.15.0-alpine3.16

# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
WORKDIR /opt/
COPY ./package.json ./yarn.lock ./
ENV PATH /opt/node_modules/.bin:$PATH
RUN yarn config set network-timeout 600000 -g && yarn install
WORKDIR /opt/app
COPY ./ .
RUN yarn build
EXPOSE 1337
CMD ["yarn", "develop"]

```
4. docker-compose
```
version: '3.5'
services:
  pg:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
  proxy:
    image: traefik:2.4.5
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.proxy/traefik.toml:/etc/traefik/traefik.toml # Just a elementary traefik config
      - ./.proxy/cert.toml:/etc/traefik/cert.toml
      - ./.proxy/certs/:/certs/
 strapi-cms:
    build:
      context: strapi-cms
      dockerfile: ./.docker/Dockerfile.dev
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_NAME: postgres
      DATABASE_USERNAME: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./strapi-cms/config:/opt/app/config
      - ./strapi-cms/src:/opt/app/src
      - ./strapi-cms/package.json:/opt/package.json
      - ./strapi-cms/yarn.lock:/opt/yarn.lock
      - ./strapi-cms/.env:/opt/app/.env
      - ./strapi-cms/public/uploads:/opt/app/public/uploads
    links:
      - pg
      - proxy:${BASE_HOST}
      - proxy:aws.${BASE_HOST}
    labels:
      traefik.tags: xxx
      traefik.enable: true

      traefik.http.routers.strapi-cms.entrypoints: web-secure
      traefik.http.routers.strapi-cms.rule: Host(`${BASE_HOST}`) && PathPrefix(`/cms`)
      traefik.http.routers.strapi-cms.tls: true
      traefik.http.routers.strapi-cms.priority: 30

    depends_on:
      - pg
```
5. Upon building strapi-cms and launching the stack, the admin panel fails to load
<img width="682" alt="image" src="https://user-images.githubusercontent.com/3440665/230106240-68859e2e-f721-4a6d-9977-282a8ff20d4d.png">

### Expected behavior
Admin panel (for start, but also all other Strapi resources) should be available behind https://xxx.local/cms

I would expect the same behavior as with subdomain configuration. That's the scenario where i configure strapi & Traefik to be behind  https://strapi-cms.xxx.local and voila, where the issue from above is nonexistent

To replicate that:
1. Remove the below from config/server.ts
```
  url: "/cms",
  proxy: true,
```
2. Adjust traefik route
```
      traefik.http.routers.strapi-cms.rule: Host(`strapi-cms.${BASE_HOST}`)
```
With the above two adjustments, the Strapi Admin can be accessed via `strapi-cms.xxx.local`.

However, the desired setup is to access Strapi via `xxx.local/cms`.
