### ISSUE TITLE
[Bug] All comboboxes aren't working

### ISSUE THREAD

**Issue by cangomescisco** [strapi/strapi#17344]
### Required System information

- Node.js version: v16.13.2
- NPM version: 
- Strapi version: 4.11.5v
- Database: Postgres
- Operating system: Linux
- Is your project Javascript or Typescript:

### Describe the bug

All combobox stopped working.

### Steps to reproduce the behavior

https://github.com/strapi/strapi/assets/99295108/45934094-62d0-4d8c-ab5b-2838098cbe26

### Expected behavior

Combobox should be working as expected here: https://design-system-git-main-strapijs.vercel.app/?path=/docs/design-system-components-combobox--creatable

### Screenshots

[If applicable, add screenshots to help explain your problem.](https://github.com/strapi/strapi/assets/99295108/45934094-62d0-4d8c-ab5b-2838098cbe26)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by candidosales** [comment]
More info about the environment: 

```bash
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

render.yaml

```yaml
services:
  - type: web
    name: strapi
    env: node
    plan: standard
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    disk:
      name: strapi-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: ~16.17.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: strapi
    plan: standard

```
