### ISSUE TITLE
Admin.ts not working with NGINX Ingress issue on subfolders hosting

### ISSUE THREAD

**Issue by PaulCorbeau** [strapi/strapi#17400]
### Required System information

- Node.js version: 18.17
- NPM version: 9.8.0
- Strapi version: 4.11.5
- Database: postgres
- Operating system: Ubuntu 22.04 LTS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I would like to deploy strapi on a Kubernetes cluster using nginx ingress.
The application works properly when I'm using subdomains : chart-example.local and chart-example.local/admin
It fails if I try to use subdirectory : chart-example.local/strapi is ok for the root of the application but chart-example.local/strapi/admin fails.
I've got 3 files that are not properly loaded with a 404 error : 

![image](https://github.com/strapi/strapi/assets/8874816/e9381a0f-80db-4d3a-a775-8f4b64c36281)

### Steps to reproduce the behavior

1 - Create a strapi app
2 - Create the docker image
3 - Deploy the application on Kubernetes or Rancher Desktop (I'm using helm)

### Expected behavior

I should be able to reach /admin on subdirectories

### Screenshots

Root page is working properly : 

![image](https://github.com/strapi/strapi/assets/8874816/33f9a87a-aae8-4ee6-8705-59164ffb94d2)

Admin page fails : 

![image](https://github.com/strapi/strapi/assets/8874816/b80cac1a-3eb8-45dd-90ae-ec8105e56f7d)

### Code snippets

This is my admin.ts:

```
export default ({ env }) => ({
  auth: {
    secret: env('ADMIN_JWT_SECRET'),
  },
  apiToken: {
    salt: env('API_TOKEN_SALT'),
  },
  transfer: {
    token: {
      salt: env('TRANSFER_TOKEN_SALT'),
    },
  },
});
```

This is my server.ts:
```
export default ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('SERVER_URL', 'http://localhost:1337'),
  proxy: env.bool('IS_PROXIED', true),
  app: {
    keys: env.array("[APP_KEYS1],[APP_KEYS2]", ["testKey1", "testKey2"]),
  },
  webhooks: {
    populateRelations: env.bool('WEBHOOKS_POPULATE_RELATIONS', false),
  }
});
```

This is my ingress configuration : 

```
# Source: order-handling-cms/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-order-handling-cms-backend-ingress
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
  labels:
    environment: "dev"
    system-component: "backend"
    helm.sh/chart: order-handling-cms-1.0.0
    app.kubernetes.io/name: order-handling-cms
    app.kubernetes.io/instance: release-name  
spec:
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: /order-handling-cms/(.*)
            pathType: Prefix
            backend:
              service:
                name: release-name-order-handling-cms-backend-svc
                port:
                  name: http
```

This is my ENV:

```
image:
  tag: v1
  repository: cms
  secretName: "order-handling-cms"
  env:
    NODE_ENV: production
    DATABASE_CLIENT: "postgres"
    DATABASE_HOST: "acid-minimal-cluster.default.svc.cluster.local"
    DATABASE_PORT: "5432"
    DATABASE_NAME: "foo"
    SERVER_URL: "http://chart-example.local/order-handling-cms"
```

This is my DOCKERFILE:

```
FROM node:18.17-alpine as BUILD
# Set NODE_ENV to production
ENV NODE_ENV=production
# Install dependencies
RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash
# Set Working Directory
WORKDIR /app
# Copy package.json and lock
COPY app/package*.json /app/
# Install dev dependencies 
RUN yarn install
# Copy app
COPY /app /app
# Build app
RUN yarn build


### RELEASE STAGE ####
FROM node:18.17-alpine as RELEASE
# Set NODE_ENV to production
ENV NODE_ENV=production
# Delete node user and add one anew. This ensures that we know the group and user ID.
# See: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#non-root-user
# Also, we install 'tini', which ensures that SIGINT (CTRL-C) is forwarded correctly
# See: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
# And: https://github.com/krallin/tini#using-tini
RUN deluser --remove-home node \
  && addgroup -S -g 1001 docker \
  && adduser -S -G docker -u 1001 appuser \
  && mkdir -p /home/appuser/srv/app/.tmp \
  && chown 1001:1001 /home/appuser/srv/app/.tmp
# Switch to newly created user
RUN chown -Rh 1001:1001 /home/appuser/srv/app
USER 1001
# Switch to newly created user's app directory
WORKDIR /home/appuser/srv/app
# Copy app
COPY --from=BUILD --chown=1001:1001 /app /home/appuser/srv/app
# Set default host and expose port 1337 (used by strapi)
ENV HOST=0.0.0.0

ARG SERVER_URL
ENV SERVER_URL=$SERVER_URL

RUN yarn build

EXPOSE 1337
# Start the application
CMD [ "yarn", "start" ]
```
