### ISSUE TITLE
Can't load admin panel in 4.12.4 on the public internet

### ISSUE THREAD

**Issue by exchgr** [strapi/strapi#17634]
### Required System information

- Node.js version: v18.17.0
- NPM version: 9.6.7
- Strapi version: 4.12.4
- Database: aurora postgres 14.6
- Operating system: the docker container node:18-alpine, `Linux 30339f198cc4 5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023 aarch64 Linux`
- Is your project Javascript or Typescript: typescript

### Describe the bug

The Strapi admin panel won't load. It shows an error banner with the text:

> Warning: An error occurred while requesting the API

Looking in the browser console, the browser also tries to make several requests to http://localhost:1337, which makes no sense on the public internet. I haven't changed any configurations between 4.12.1 and 4.12.4.

### Steps to reproduce the behavior

1. Visit a strapi admin panel deployed to an environment other than localhost

### Expected behavior

The admin panel loads.

### Screenshots

(hostname of my server redacted for privacy)
<img width="1280" alt="Screenshot 2023-08-09 at 6 09 02 PM" src="https://github.com/strapi/strapi/assets/824678/035aaaa5-42a3-4af2-b45d-70234d5e881d">

### Code snippets

n/a

### Additional context

I tried setting `STRAPI_ADMIN_BACKEND_URL` manually to the domain where my strapi server is, but it didn't work.

**Comment by exneval** [comment]
I have the same problem and same error, 4.12.4

**Comment by cannorin** [comment]
We've encountered the same issue by *not* upgrading strapi to v4.12.4, but rather upgrading `@strapi/design-system` to v1.9.0. Downgrading `@strapi/design-system` to v1.8.2 fixed the problem.

(We've also upgraded `@strapi/icons` to v1.9.0 and also downgraded it to v1.8.2, but I guess this shouldn't matter as it only provides icons...)

**Comment by Cretezy** [comment]
Can also confirm, after upgrading to 4.12.4 from 4.12.1.

```diff
-        "@strapi/plugin-graphql": "^4.12.1",
-        "@strapi/plugin-i18n": "4.12.1",
-        "@strapi/plugin-users-permissions": "4.12.1",
-        "@strapi/strapi": "4.12.1",
+        "@strapi/plugin-graphql": "^4.12.4",
+        "@strapi/plugin-i18n": "4.12.4",
+        "@strapi/plugin-users-permissions": "4.12.4",
+        "@strapi/strapi": "4.12.4",
```

**Comment by joshuaellis** [comment]
I've just tried to create a new strapi-app with `npx create-strapi-app@latest` and did not run into this issue, i'll check the upgrade path now but can I confirm when you updated your strapi app you re-ran the build command to ensure the admin panel is rebuilt? :)

**Comment by gu-stav** [comment]
I can confirm what ⬆️ @joshuaellis said. Could you please try and delete your `node_modules` directory and run `yarn build && yarn develop` again?

I was able to make `STRAPI_ADMIN_BACKEND_URL` work that way.

**Comment by cannorin** [comment]
@joshuaellis @exchgr In our case, we always build a Docker image and push it to our server, which involves 1) `yarn install` and 2) `yarn build`.

Also, we don't set `STRAPI_ADMIN_BACKEND_URL`. We haven't encountered any problem on v4.12.1 and before.

**Comment by exneval** [comment]
it's really unfortunate that in local environment everything is fine

it's only happened when you trying to host it in the server
I'm using strapi with dockerize container

**Comment by cannorin** [comment]
Yes, you would have to deploy it to somewhere to reproduce it.

**Comment by gu-stav** [comment]
I have tried running Strapi in Docker and mapped port 1337 to 1339, which is working well too:

<img width="985" alt="Screenshot 2023-08-10 at 09 36 30" src="https://github.com/strapi/strapi/assets/2244375/e7a1ba58-293e-4770-8830-a79f117c822f">

```yaml
version: '3'
services:
  strapi:
    container_name: strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1339:1337'
    networks:
      - strapi
    depends_on:
      - strapiDB
```

I think that should be sufficient to see the bug mentioned?
