### ISSUE TITLE
The email configuration cannot be adjusted

### ISSUE THREAD

**Issue by tobiasbenkner** [strapi/strapi#17949]
### Required System information
- Node.js version: v18.12.1
- NPM version: 9.8.0
- Strapi version: 4.13.2
- Database: doesn't matter
- Operating system: macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug
I cannot adjust the email configuration. The configuration will be ignored from Strapi.

I was follwing the docs from Strapi
- https://docs.strapi.io/dev-docs/plugins/email
- https://docs.strapi.io/dev-docs/providers
- https://www.npmjs.com/package/@strapi/provider-email-nodemailer

I was trying to place the plugins.ts into two different folders. It doesn't work:
- config/plugins.ts
- config/env/development/plugins.ts

Also i was changing the provider name to:
- nodemailer
- strapi-provider-email-nodemailer

both doesn't work.

### Steps to reproduce the behavior

1. Checkout https://github.com/tobiasbenkner/strapi-bug-nodemailer
2. yarn
3. yarn develop
4. Go to http://localhost:1337/admin/settings/email

### Expected behavior
you will see that the email provider is still sendmail instead of nodemailer

### Code snippets
./config/plugins.ts
```
export default ({ env }) => {
  return {
    email: {
      // provider: 'nodemailer',
      provider: 'strapi-provider-email-nodemailer',
      providerOptions: {
        host: 'localhost',
        port: 1025,
        ignoreTLS: true,
      },
    },
  };
};
```

./package.json
```
"@strapi/provider-email-nodemailer": "^4.13.2",
"nodemailer": "^6.9.5"
```

### Additional context
./docker-compose.yml for mocking an smtp server
```
version: '3.1'

volumes:
  mail:
  
services:

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - mail:/home/mailhog
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog
```
