### ISSUE TITLE
Building the admin dependencies error

### ISSUE THREAD

**Issue by stephane-r** [strapi/strapi#1840]
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: > 5
- **Strapi version**: latest
- **Database**: mongo
- **Operating system**: gitlab-ci, docker image node:9.11.1-alpine

**What is the current behavior?**

I would like run build step via Gitlab-Ci, but the admin building step return an error :

```
Administration Panel
📦 Installing packages...
Packaged installed successfully

> strapi-admin@3.0.0-alpha.13.1 setup /builds/user/project/strapi-app/admin
> node ./scripts/setup.js

🏗 Building the admin...
internal/modules/cjs/loader.js:550
throw err;
^

Error: Cannot find module 'immutable'
```

**Steps to reproduce the problem**

You can see my gitlab-ci.yml build config :

```
build:
  image: node:9.11.1-alpine
  stage: build
  script:
    - apk --update add g++ make bash zlib-dev libpng-dev git autoconf automake build-base libtool nasm python2 python
    - cd strapi-app
    - npm i
    - npm run setup
  artifacts:
    expire_in: 1 day
    paths:
      - dist
```

**What is the expected behavior?**

I've try same step with same node version of my build config on my Ubuntu Os (not Linux alpine) and all step work... 

I've this error only on gitlab ci

Anyone can help me ?

Thank you community !
