### ISSUE TITLE
Docker container crashes: The Strapi admin needs to install not required react and other packages

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#18648]
```
 => ERROR [strapi 10/10] RUN ["yarn", "build"]                                                                             1.1s
------
 > [strapi 10/10] RUN ["yarn", "build"]:
0.227 yarn run v1.22.19
0.246 $ strapi build
1.076 [INFO] The Strapi admin needs to install the following dependencies:
1.076    - react@^18.0.0
1.076   - react-dom@^18.0.0
1.076   - react-router-dom@^5.0.0
1.076   - styled-components@^5.0.0
1.080 ? Would you like to install these dependencies now? These are not required but
1.080 are recommended, from V5 these will be required. (Y/n)                                                                   error Command failed with signal "SIGINT".
1.096 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "yarn build" did not complete successfully: exit code: 1
```

I can't build my container now.

My package.json for Strapi:

```
{
  "name": "strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "dev": "strapi dev",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-graphql": "^4.15.0",
    "@strapi/plugin-documentation": "^4.15.0",
    "@strapi/plugin-i18n": "^4.15.0",
    "@strapi/plugin-users-permissions": "^4.15.0",
    "@strapi/strapi": "^4.15.0",
    "pg": "^8.11.3"
  }
}

```

**Comment by joshuaellis** [comment]
Thanks for the report! So you're trying to build strapi, what's your NODE_ENV?

**Comment by teinett** [comment]
NODE_ENV: development

**Comment by teinett** [comment]
I am not deploying. I do it on my local machine.

docker-compose.yml:
```
version: '3'

services:


  strapi:
    build: 
      context: .
      dockerfile: ./dockerfiles/strapi.dockerfile
    image: strapi:latest
    container_name: strapi_${PROJECT_NAME}
    ports:
      - "1337:1337"
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - database
      - redis
    environment:
      NODE_ENV: development
      DB_HOST: database
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    volumes:
      - ./strapi/config:/strapi/app/config
      - ./strapi/src:/strapi/app/src
      - ./strapi/package.json:/strapi/package.json
      - ./strapi/yarn.lock:/strapi/yarn.lock
      - ./.env:/strapi/app/.env
      - ./strapi/public:/strapi/app/public
      - ./strapi/public/uploads:/strapi/app/public/uploads
    networks:
      - strapi-astro-network

  database:
    image: postgres:14-alpine
    platform: linux/amd64 #for platform error on Apple M1 chips
    container_name: postgres_${PROJECT_NAME}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapi-astro-network

networks:
  strapi-astro-network:
    driver: bridge

```
