### ISSUE TITLE
yarn develop -> Cannot destructure property 'client' of 'db.config.connection' as it is undefined

### ISSUE THREAD

**Issue by vitakili** [strapi/strapi#18920]
Full error log even after --debug is ->
│   TypeError: Cannot destructure property 'client' of 'db.config.connection' as it is undefined.                                                       │
│       at getDialect (D:\nextjs_strapi\vita-multilang\portfolio-backend\node_modules\@strapi\database\dist\index.js:1014:11)                           │
│       at new Database (D:\nextjs_strapi\vita-multilang\portfolio-backend\node_modules\@strapi\database\dist\index.js:6114:20)                         │
│       at Database.init (D:\nextjs_strapi\vita-multilang\portfolio-backend\node_modules\@strapi\database\dist\index.js:6100:16)                        │
│       at Strapi.bootstrap (D:\nextjs_strapi\vita-multilang\portfolio-backend\node_modules\@strapi\strapi\dist\Strapi.js:365:39)                       │
│       at Strapi.load (D:\nextjs_strapi\vita-multilang\portfolio-backend\node_modules\@strapi\strapi\dist\Strapi.js:419:16)                            │
│       at async Object.develop (D:\nextjs_strapi\vita-multilang\portfolio-backend\node_modules\@strapi\admin\dist\_chunks\index-cce8ecb6.js:1160:28)   │
│       at async develop (D:\nextjs_strapi\vita-multilang\portfolio-backend\node_modules\@strapi\admin\dist\_chunks\develop-69e28e61.js:52:5)           │
│       at async Command.parseAsync (D:\nextjs_strapi\vita-multilang\portfolio-backend\node_modules\commander\lib\command.js:923:5)                     │
│       at async Module.runStrapiCommand (D:\nextjs_strapi\vita-multilang\portfolio-backend\node_modules\@strapi\strapi\dist\commands\index.js:124:3) 
-->

## Bug report

- Node.js version: v18.18.2
- Yarn version: 1.22.19
- Strapi version:4.13.6/4.15.4 (doesn't matter -> both same error)
- Database: postgres
- Operating system: win32-x64
- Is your project Javascript or Typescript: ts

### Steps to reproduce the behavior

1. type **yarn build && yarn develop**
2. look at error
3. 8 times delete node_modules and change versions of Strapi
4. See error again

### Expected behavior

Development server -> localhost:1337

**Comment by zguig52** [comment]
@djakaitis seems the doc is KO.

**Comment by exotexot** [comment]
The same issue also exists in the JS version ...

**Comment by sebammon** [comment]
We're experiencing this issue when running tests for strapi using jest.

**Comment by parsagholipour** [comment]
Same experience

**Comment by jhsu98** [comment]
also running into this trying to use jest locally

**Comment by shfx** [comment]
I found that when you use TS, Strapi is looking for a `dist` dir (the one from `tsconfig.json`) while looking for the config. I was trying to tinker with `tsconfig.json` and enabled "noEmit". This resulted in a similar situation. Hope that helps. You might have typescript pipeline broken for some reason.

**Comment by richardgotthard** [comment]
Facing same problem, anyone have an update on this with typescript.

**Comment by sebammon** [comment]
FWIW, I was able to solve this issue for the case of running strapi programmatically when testing with jest. As @shfx mentioned, when you use TS, Strapi is looking for a `dist` dir. So following [the docs](https://docs.strapi.io/dev-docs/typescript#start-strapi-programmatically):
```diff
const Strapi = require("@strapi/strapi");

async function setupStrapi() {
  ...
-  await Strapi().load();
+  await Strapi.compile().then((appContext) => Strapi(appContext).load());
  ...
}
```

**Comment by gilliardmacedo** [comment]
It happened to me when I was launching an existing project into another repo and another environment. My gitignore template removed tsconfig.json so it didn't exist in CI environment. Removing that line from gitignore solved it

**Comment by sfarkas1988** [comment]
I can confirm that this issue exists only when using strapi with TS.
I can reproduce it by:

`yarn build && node server.js`

It does not work when strapi is initiated with TS.
It does work when strapi is initiated without TS.

**Comment by rkristelijn** [comment]
I got this error: `Cannot destructure property 'client' of 'db.config.connection' as it is undefined` and I fixed it. Maybe my steps to fix will help other people.

# Situation:
I had a docker image where I copied over selective folders from strapi. I go the above error. The cause was that `tsconfig.json` was missing
```yaml
FROM node:20-alpine

ARG WORKDIR=/app
WORKDIR $WORKDIR

# Prepare the environment
ENV NODE_ENV=production

# We need only strapi dependencies which are contained in apps/portal-service
COPY apps/portal-service/package.json package-lock.json ./
# Note: NODE_ENV=production is set to avoid installing devDependencies,
#  npm i installs only (production) dependencies
RUN npm i --legacy-peer-deps

# We need only strapi which is contained in apps/portal-service
COPY apps/portal-service/config /app/config
COPY apps/portal-service/public /app/public

# The build is done outside of docker
COPY apps/portal-service/dist /app/dist
COPY apps/portal-service/tsconfig.json /app # << this was missing

EXPOSE 1337

# For debugging; uncomment below to run indefinitely without errors
# CMD ["tail", "-f", "/dev/null"]

# Original command
CMD ["npm", "start"]
```

**Comment by LordOfInternet** [comment]
I am getting the same error and I am using js.

**Comment by tirthshah574** [comment]
Hello @shfx @sfarkas1988 @djakaitis @derrickmehaffy @exotexot,

I was able to solve this issue. It turns out that a configuration in TypeScript caused the problem. All we need to do is remove "noEmit": true from tsconfig.json.

**Comment by enesbala5** [comment]
Can you please post a working tsconfig.json file?

**Comment by tirthshah574** [comment]
@enesbala5 

There you go

> tsconfig.json

`{
  "extends": "@strapi/typescript-utils/tsconfigs/server",
  "compilerOptions": {
    "outDir": "dist",
    "rootDir": ".",
    "lib": ["esnext", "dom"],
    "skipLibCheck": true, // Skip type checking of declaration files
    "strict": false, // Disable strict type checking
    "allowJs": true, // Allow JavaScript files to be compiled
    "checkJs": false, // Disable checking JavaScript files
    "noImplicitAny": false,
    "noImplicitThis": false
  },
  "include": [
    "./",
    "./**/*.ts",
    "./**/*.js",
    "src/**/*.json",
  ],
  "exclude": [
    "node_modules/",
    "build/",
    "dist/",
    ".cache/",
    ".tmp/",
    "src/admin/",
    "**/*.test.ts",
    "src/plugins/**",
    "types/generated/**"
  ]
}
`

**Comment by Maclay74** [comment]
I have the same problem even with this config.

**Comment by HerrSammyDE** [comment]
same here

**Comment by tirthshah574** [comment]
@Maclay74 @HerrSammyDE 
I'm using Postgres and it works for me. I am attaching db config for your reference.


> config/database.ts

```
export default ({ env }) => ({
  connection: {
    client: 'postgres',
    connection: {
      host: env('DATABASE_HOST'),
      port: env.int('DATABASE_PORT'),
      database: env('DATABASE_NAME'),
      schema: env('DATABASE_SCHEMA'),
      user: env('DATABASE_USERNAME'),
      password: env('DATABASE_PASSWORD'),
      ssl: env.bool('DATABASE_SSL'),
    },
  },
});

```

**Comment by HerrSammyDE** [comment]
Hey @tirthshah574, thanks for your help! I have shortened the file to the minimum, unfortunately without success. I still get the same error.

I have attached further files below.

```
const path = require('path');

module.exports = ({ env }) => {
  const client = 'mysql';

  const connection = {
    host: env('DATABASE_HOST'),
    port: env.int('DATABASE_PORT'),
    database: env('DATABASE_NAME'),
    user: env('DATABASE_USERNAME'),
    password: env('DATABASE_PASSWORD'),
    ssl: env.bool('DATABASE_SSL', false) && {
      key: env('DATABASE_SSL_KEY', undefined),
      cert: env('DATABASE_SSL_CERT', undefined),
      ca: env('DATABASE_SSL_CA', undefined),
      capath: env('DATABASE_SSL_CAPATH', undefined),
      cipher: env('DATABASE_SSL_CIPHER', undefined),
      rejectUnauthorized: env.bool(
        'DATABASE_SSL_REJECT_UNAUTHORIZED',
        true
      ),
    },
  };

  const pool = {
    min: env.int('DATABASE_POOL_MIN', 2),
    max: env.int('DATABASE_POOL_MAX', 10)
  };

  return {
    connection: {
      client,
      connection,
      pool,
      acquireConnectionTimeout: env.int('DATABASE_CONNECTION_TIMEOUT', 60000),
    },
  };
};
```

---

Here is my Docker compose and my .env file - censored of course.

Docker compose
```
version: "3"

services:
  strapi:
    container_name: strapi
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
      STRAPI_TELEMETRY_DISABLED: ${STRAPI_TELEMETRY_DISABLED}
    volumes:
      - /opt/strapi/config:/opt/app/config
      - /opt/strapi/src:/opt/app/src
      - /opt/strapi/package.json:/opt/package.json
      - /opt/strapi/yarn.lock:/opt/yarn.lock
      - /opt/strapi/.env:/opt/app/.env
      - /opt/strapi/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi

networks:
  strapi:
    name: Strapi
    driver: bridge
```

.env
```
NODE_ENV=production

HOST=0.0.0.0
PORT=1337

# App keys
APP_KEYS="toBeModified1,toBeModified2"
API_TOKEN_SALT=tobemodified
ADMIN_JWT_SECRET=tobemodified
TRANSFER_TOKEN_SALT=tobemodified
JWT_SECRET=tobemodified

# Database
DATABASE_CLIENT=mysql
DATABASE_HOST=
DATABASE_PORT=3306
DATABASE_NAME=
DATABASE_USERNAME=
DATABASE_PASSWORD=

# Optional
STRAPI_TELEMETRY_DISABLED=false
```
