### ISSUE TITLE
`strapi@4.20.4` build failing

### ISSUE THREAD

**Issue by ProfXponent** [strapi/strapi#19727]
`strapi@4.20.4` build is failing

we run strapi in a docker container and don't externally mount `node_modules` so its a fresh install every time `package.json` changes.

getting the following error after upgrading to `strapi@4.20.4`

```shell
cms        | [ERROR] Module not found: Error: Can't resolve '@strapi/design-system/Box' in '/opt/app/node_modules/@strapi/plugin-seo/admin/src/components/CMEditView/RightLinksCompo'
```

starting with `strapi develop --debug` yields

```shell
cms  | 
cms  | > cms@0.1.0 develop
cms  | > strapi develop --debug
cms  | 
cms  | [DEBUG] Loaded package.json: 
cms  |  {
cms  |   name: 'cms',
cms  |   version: '0.1.0',
cms  |   description: 'A Strapi application',
cms  |   scripts: {
cms  |     develop: 'strapi develop --debug',
cms  |     start: 'strapi start',
cms  |     build: 'strapi build',
cms  |     strapi: 'strapi',
cms  |     import: 'strapi import --file ./seeds/seed-data.tar.gz',
cms  |     export: 'strapi export --no-encrypt --file ./exports/export'
cms  |   },
cms  |   dependencies: {
cms  |     '@strapi/plugin-documentation': '4.20.4',
cms  |     '@strapi/plugin-i18n': '4.20.4',
cms  |     '@strapi/plugin-seo': '1.9.8',
cms  |     '@strapi/plugin-users-permissions': '4.20.4',
cms  |     '@strapi/provider-email-sendgrid': '4.20.4',
cms  |     '@strapi/strapi': '4.20.4',
cms  |     react: '18.2.0',
cms  |     'react-dom': '18.2.0',
cms  |     'react-router-dom': '5.3.4',
cms  |     'styled-components': '5.3.11',
cms  |     'better-sqlite3': '9.4.3'
cms  |   },
cms  |   strapi: { uuid: '42b937aa-0f16-4a30-bb55-95f60ec03b48' },
cms  |   engines: { node: '>=14.19.1 <=18.x.x', npm: '>=6.0.0' },
cms  |   readme: 'ERROR: No README data found!',
cms  |   _id: 'cms@0.1.0'
cms  | }
cms  | 
cms  | - Building build context
cms  | [INFO] Including the following ENV variables as part of the JS bundle:
cms  |     - ADMIN_PATH
cms  |     - STRAPI_ADMIN_BACKEND_URL
cms  |     - STRAPI_TELEMETRY_DISABLED
cms  | [DEBUG] Cleaning dist folder: /opt/app/build
cms  | [DEBUG] Cleaned dist folder
cms  | [DEBUG] Dependencies from user's project 
cms  |  {
cms  |   '@strapi/plugin-documentation': '4.20.4',
cms  |   '@strapi/plugin-i18n': '4.20.4',
cms  |   '@strapi/plugin-seo': '1.9.8',
cms  |   '@strapi/plugin-users-permissions': '4.20.4',
cms  |   '@strapi/provider-email-sendgrid': '4.20.4',
cms  |   '@strapi/strapi': '4.20.4',
cms  |   react: '18.2.0',
cms  |   'react-dom': '18.2.0',
cms  |   'react-router-dom': '5.3.4',
cms  |   'styled-components': '5.3.11',
cms  |   'better-sqlite3': '9.4.3'
cms  | }
cms  | [DEBUG] User's plugins file 
cms  |  {
cms  |   seo: { enabled: true },
cms  |   email: {
cms  |     config: {
cms  |       provider: 'sendgrid',
cms  |       providerOptions: [Object],
cms  |       settings: [Object]
cms  |     }
cms  |   },
cms  |   documentation: {
cms  |     enabled: true,
cms  |     config: {
cms  |       openapi: '3.0.0',
cms  |       info: [Object],
cms  |       'x-strapi-config': [Object],
cms  |       servers: [Array],
cms  |       externalDocs: [Object],
cms  |       security: [Array]
cms  |     }
cms  |   }
cms  | }
cms  | [DEBUG] Enabled plugins 
cms  |  {
cms  |   documentation: {
cms  |     name: 'documentation',
cms  |     importName: 'documentation',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-documentation'
cms  |   },
cms  |   i18n: {
cms  |     name: 'i18n',
cms  |     importName: 'i18N',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-i18n'
cms  |   },
cms  |   seo: {
cms  |     name: 'seo',
cms  |     importName: 'seo',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-seo'
cms  |   },
cms  |   'users-permissions': {
cms  |     name: 'users-permissions',
cms  |     importName: 'usersPermissions',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-users-permissions'
cms  |   }
cms  | }
cms  | [DEBUG] Enabled plugins with FE 
cms  |  [
cms  |   {
cms  |     name: 'documentation',
cms  |     importName: 'documentation',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-documentation/strapi-admin'
cms  |   },
cms  |   {
cms  |     name: 'i18n',
cms  |     importName: 'i18N',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-i18n/strapi-admin'
cms  |   },
cms  |   {
cms  |     name: 'seo',
cms  |     importName: 'seo',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-seo/strapi-admin'
cms  |   },
cms  |   {
cms  |     name: 'users-permissions',
cms  |     importName: 'usersPermissions',
cms  |     type: 'module',
cms  |     modulePath: '@strapi/plugin-users-permissions/strapi-admin'
cms  |   }
cms  | ]
cms  | ✔ Building build context (74ms)
cms  | - Creating admin
cms  | [DEBUG] Created the runtime directory
cms  | [DEBUG] Rendered the HTML
cms  | [DEBUG] Wrote the index.html file
cms  | [DEBUG] Wrote the app.js file
cms  | [DEBUG] Webpack config {
cms  |   experiments: { topLevelAwait: true },
cms  |   entry: { main: [ './.strapi/client/app.js' ] },
cms  |   resolve: {
cms  |     alias: {
cms  |       '@strapi/design-system$': '/opt/app/node_modules/@strapi/admin/node_modules/@strapi/design-system',
cms  |       '@strapi/helper-plugin$': '/opt/app/node_modules/@strapi/admin/node_modules/@strapi/helper-plugin',
cms  |       '@strapi/icons$': '/opt/app/node_modules/@strapi/admin/node_modules/@strapi/icons',
cms  |       'date-fns$': '/opt/app/node_modules/date-fns',
cms  |       'formik$': '/opt/app/node_modules/formik',
cms  |       'history$': '/opt/app/node_modules/history',
cms  |       'immer$': '/opt/app/node_modules/immer',
cms  |       'qs$': '/opt/app/node_modules/qs',
cms  |       'lodash$': '/opt/app/node_modules/lodash',
cms  |       'react$': '/opt/app/node_modules/react',
cms  |       'react-dnd$': '/opt/app/node_modules/react-dnd',
cms  |       'react-dnd-html5-backend$': '/opt/app/node_modules/react-dnd-html5-backend',
cms  |       'react-dom$': '/opt/app/node_modules/react-dom',
cms  |       'react-error-boundary$': '/opt/app/node_modules/react-error-boundary',
cms  |       'react-helmet$': '/opt/app/node_modules/react-helmet',
cms  |       'react-is$': '/opt/app/node_modules/react-is',
cms  |       'react-intl$': '/opt/app/node_modules/react-intl',
cms  |       'react-query$': '/opt/app/node_modules/react-query',
cms  |       'react-redux$': '/opt/app/node_modules/react-redux',
cms  |       'react-router-dom$': '/opt/app/node_modules/react-router-dom',
cms  |       'react-window$': '/opt/app/node_modules/react-window',
cms  |       'react-select$': '/opt/app/node_modules/react-select',
cms  |       'redux$': '/opt/app/node_modules/redux',
cms  |       'reselect$': '/opt/app/node_modules/reselect',
cms  |       'styled-components$': '/opt/app/node_modules/styled-components',
cms  |       'yup$': '/opt/app/node_modules/yup'
cms  |     },
cms  |     extensions: [ '.js', '.jsx', '.react.js', '.ts', '.tsx' ]
cms  |   },
cms  |   module: {
cms  |     rules: [
cms  |       [Object], [Object],
cms  |       [Object], [Object],
cms  |       [Object], [Object],
cms  |       [Object]
cms  |     ]
cms  |   },
cms  |   plugins: [
cms  |     HtmlWebpackPlugin {
cms  |       userOptions: [Object],
cms  |       version: 5,
cms  |       options: [Object]
cms  |     },
cms  |     DefinePlugin { definitions: [Object] },
cms  |     MiniCssExtractPlugin {
cms  |       _sortedModulesCache: [WeakMap],
cms  |       options: [Object],
cms  |       runtimeOptions: [Object]
cms  |     }
cms  |   ],
cms  |   stats: 'errors-only',
cms  |   mode: 'production',
cms  |   bail: true,
cms  |   devtool: false,
cms  |   output: {
cms  |     path: '/opt/app/build',
cms  |     publicPath: '/admin/',
cms  |     filename: '[name].[contenthash:8].js',
cms  |     chunkFilename: '[name].[contenthash:8].chunk.js'
cms  |   },
cms  |   optimization: {
cms  |     minimize: undefined,
cms  |     minimizer: [ [ESBuildMinifyPlugin] ],
cms  |     moduleIds: 'deterministic',
cms  |     runtimeChunk: true
cms  |   }
cms  | }
cms  | [ERROR] Module not found: Error: Can't resolve '@strapi/icons/Search' in '/opt/app/node_modules/@strapi/plugin-seo/admin/src/components/PluginIcon'
cms  | [ERROR]  There seems to be an unexpected error, try again with --debug for more information 
```

I'm including my `Dockerfile`, `package.json`, and `package-lock.json` if anyone wants to replicate this.

Already cleared my image cache and rebuild from scratch a few times.

Below is a `docker-compose.yaml` snippet you can use with the included `Dockerfile`

```Dockerfile
ARG NODE_VERSION
FROM node:${NODE_VERSION}
RUN mkdir -p /opt/app
RUN chown -R node:node /opt/app
# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add curl bash build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev

USER node

WORKDIR /opt/app
ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}
COPY --chown=node:node package.json package-lock.json ./
RUN npm install
ENV PATH /opt/app/node_modules/.bin:$PATH
COPY --chown=node:node config ./config
COPY --chown=node:node database ./database
COPY --chown=node:node public ./public
COPY --chown=node:node src ./src
COPY --chown=node:node favicon.png ./favicon.png

CMD ["npm", "run", "develop"]
```

```yaml
services:
  strapi-cms:
    container_name: strapi-cms
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 18-alpine3.19
        NODE_ENV: development
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 10
    restart: unless-stopped
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: database/data.db
      DATABASE_HOST: db
      JWT_SECRET: aaa
      ADMIN_JWT_SECRET: bbb
      SENDGRID_API_KEY: ccc
      SENDGRID_SENDER_EMAIL: ddd
      APP_KEYS: eee,fff,ggg,hhh
      API_TOKEN_SALT: iii
      TRANSFER_TOKEN_SALT: jjj
      WEB_URL: http://web-container:3000
      CMS_URL: http://strapi-cms:1337
    volumes:
      - ./config:/opt/app/config
      - ./database:/opt/app/database
      - ./public:/opt/app/public
      - ./src:/opt/app/src
      - ./favicon.png:/opt/app/favicon.png
      - ./seeds:/opt/app/seeds:ro
      - ./exports:/opt/app/exports
      - ./package.json:/opt/app/package.json
      - ./package-lock.json:/opt/app/package-lock.json
```

[package-lock.json](https://github.com/strapi/strapi/files/14556743/package-lock.json)
[package.json](https://github.com/strapi/strapi/files/14556744/package.json)

_Originally posted by @ProfXponent in https://github.com/strapi/strapi/issues/19686#issuecomment-1988051801_
