### ISSUE TITLE
Error when deploy to Google App Engine

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#2146]
**Informations**
- **Node.js version**: v10.0.0
- **npm version**: v6.0.0
- **Strapi version**: v3.0.0-alpha.16
- **Database**: MongoDB
- **Operating system**: at Google Cloud

**What is the current behavior?**

After deploy the app:

```
textPayload:  "Error: Cannot find module 'immutable'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/plugins/content-type-builder/services/ContentTypeBuilder.js:7:31)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)" 
```

![screenshot 2018-10-15 at 16 51 03](https://user-images.githubusercontent.com/1007051/46958692-b4b37180-d09a-11e8-851e-d6afe10e02b2.png)

**Steps to reproduce the problem**

Deploy the app and go to https://project-id.appspot.com/

**What is the expected behavior?**

Working directly.

**Comment by lauriejim** [comment]
@abdonrd Can you try with npm 6 ?

**Comment by lauriejim** [comment]
And can you give me steps you did with Google Cloud Platform to deploy your app please.

**Comment by abdonrd** [comment]
I just tried with npm 6, but the same behaviour.

Steps:

1. Add `app.yaml` file:

```
runtime: nodejs8
```

2. Update the `engines` option from `package.json` to:

```
  "engines": {
    "node": "^8.0.0",
    "npm": "^6.0.0"
  },
```

3. Run this command:
```
gcloud app deploy app.yaml
```

**Comment by jinnkhan88** [comment]
@abdonrd what you can do is put the complete code on the google app engine by changing the cloud ignore files and putting up node_modules folder on the server as well.

**Comment by abdonrd** [comment]
@jinnkhan88 I can't:

```
ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: This deployment has too many files. New versions are limited to 10000 files for this app.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: This deployment has too many files. New versions are limited to 10000
      files for this app.
    field: version.deployment.files[...]
```

**Comment by jinnkhan88** [comment]
@abdonrd Apologies i just read that you are using Standard environment. Can you try using the flex environment? as this works for me

**Comment by abdonrd** [comment]
@jinnkhan88 right now I'm not interested in the flexible environment because pricing. I want to use the standard environment.

https://cloud.google.com/appengine/docs/the-appengine-environments

**Comment by jinnkhan88** [comment]
@abdonrd oh alright. I did the deployment on Flex after messing around with standard environment. As i was facing the same issues. However once on flex it was all good.

**Comment by karimation** [comment]
same here.

**Comment by abdonrd** [comment]
Same issue with the new App Engine version supported:

```
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
```

**Comment by oacstevens** [comment]
Looks like in the more limited standard app engine environment the `postinstall` script isn't run, only basic `npm install`, which leaves the plugins without dependencies. In the flex environment the build script does run, so it all gets setup correctly.

**Comment by fidelsam1992** [comment]
I was facing a similar issue trying to deploy it using a docker container.

You need to include the npm dependencies that are in the /plugins/*/package.json 
in your main package.json

I manually copied those dependencies into the main package.json file, all went good 

node -v : v10.14

**Comment by abdonrd** [comment]
I just tried to copy the plugins dependencies to the main package.json, but it has not worked for me either. 😢

**Comment by maxdyy** [comment]
Unfortunately same here 😔
Flexible ENV, runtime: nodejs10
Moved all the dependencies and dev dependencies from admin and plugins but still getting 500 server error.

![screenshot 2018-12-07 at 00 18 55](https://user-images.githubusercontent.com/25328501/49617639-b8d28000-f9b5-11e8-82ec-6fe432f3dc55.jpg)

**Comment by maxdyy** [comment]
> It's working for me (WITH FLEX) and the last version. My app.yaml file:
> 
> ```
> env: flex
> runtime: nodejs
> ```

Are you also running your db on google cloud?

**Comment by abdonrd** [comment]
Thanks to the Google Cloud team, now I have an update: we can add this to run the `postinstall`:

```
"gcp-build": "npm run postinstall",
```

But Strapi uses a lot of memory, so we also need to use a bigger [instance class](https://cloud.google.com/appengine/docs/standard/#instance_classes) in `app.yaml`:

```
runtime: nodejs10
instance_class: F2
```

And still, we find more issues about GraphQL... 😢 

<img width="1440" alt="screenshot 2018-12-14 at 18 38 16" src="https://user-images.githubusercontent.com/1007051/50018401-791c2180-ffcf-11e8-8d39-8162acc2968e.png">

**Comment by derrickmehaffy** [comment]
@abdonrd "a lot" of memory :rofl: 

![image](https://user-images.githubusercontent.com/8593673/50018752-943b6100-ffd0-11e8-849c-34e8ae68a5e4.png)


As for GraphQL, did you try running a project you have already generated everything? I'm guessing that GAE is similar to heroku with a read-only file system. So you won't be able to make file based modifications. If you run your strapi app locally, let it generate the schema files, push into git then deploy on GAE it should work.

**Comment by abdonrd** [comment]
@derrickmehaffy currently I have the entire project generated. 😕

**Comment by derrickmehaffy** [comment]
@abdonrd stupid question but you are passing the production node_env variable right?

**Comment by abdonrd** [comment]
@derrickmehaffy yes!

```yaml
runtime: nodejs10
instance_class: F2

env_variables:
  NODE_ENV: staging
  DATABASE_URI: 'xxx'
```

**Comment by abdonrd** [comment]
@lauriejim can you reopen it? 😅 

<img width="1191" alt="screenshot 2019-01-16 at 13 51 53" src="https://user-images.githubusercontent.com/1007051/51250222-028b8e80-1996-11e9-8cce-3c9b35834196.png">

**Comment by abdonrd** [comment]
https://github.com/strapi/strapi/blob/94c2f0e99997073ec88be40dc520b10ffd8b2d02/packages/strapi/lib/core/admin.js#L61-L67

Is this? I'm not sure how all Strapi works internally.

**Comment by Temmermans** [comment]
@abdonrd did you manage to deploy? I get a 500 server error after deploying with following message:
![image](https://user-images.githubusercontent.com/14975555/56113590-98679300-5f5e-11e9-944e-6d1e53ac1349.png)
Could you share the app.yaml file you used for the deployment? Any other config that needs to happen?

**Comment by abdonrd** [comment]
@Temmermans The `app.yml`:

```
runtime: nodejs10
instance_class: F2

env_variables:
  NODE_ENV: production
```

Also in the `package.json` add this script:

```
"gcp-build": "npm run postinstall",
```

**Comment by me6iaton** [comment]
@abdonrd i set "production": true in config/environments/production/server.json and it work, see 
https://github.com/strapi/strapi/pull/2518/files.  In F1 too. 
I think strapi must respect NODE_ENV: 'production' directly

**Comment by jeremyrajan** [comment]
Hi,

Do you guys any example on the `app.yaml` to use? I have this, but not sure if its entirely correct. Still can't get it to run:

```
env: flex
runtime: nodejs
service: default
env_variables:
  DATABASE_HOST: "<HOST>"
  DATABASE_PORT: 3306
  DATABASE_NAME: "<NAME>"
  DATABASE_USERNAME: "<USERNAME>"
  DATABASE_PASSWORD: "<PASSWORD>"
  DATABASE_SRV: false
  DATABASE_AUTHENTICATION_DATABASE: "admin"
  DATABASE_SSL: false
  NODE_ENV: "production"
```

Any help will be really appreciated :).

Thank you!

**Comment by Lith** [comment]
@jeremyrajan : Please find below the full configuration of my Strapi API Instance on GCP (beta.14). My SQL instance is also on GCP Cloud SQL, so maybe you don't need `beta_settings`.

I run `yarn run deploy-production` to deploy manually from my computer , but I've also implement with GitLab CI an auto-deployment on `master` branch.

`app.yaml` :
```yaml
env: flex
runtime: nodejs

# The following env variables may contain sensitive information that grants
# anyone access to your database. Do not add this file to your source control.
env_variables:
  NODE_ENV: production
  SQL_HOST: "<IP_HOST>"
  SQL_PORT: 3306
  SQL_USER:  "<USERNAME>"
  SQL_PASSWORD: "<PASSWORD>"
  SQL_DATABASE: "<DATABASE_NAME>"
  CLOUD_SQL_CONNECTION_NAME: "<CLOUD_SQL_INSTANCE_NAME>" // OPTIONAL
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: "<CLOUD_SQL_INSTANCE_NAME>" // OPTIONAL
```

`package.json` :
```json
...
  "scripts": {
    "develop": "strapi develop",
    "start": "node server.js",
    "build": "strapi build",
    "strapi": "strapi",
    "lint": "node_modules/.bin/eslint api/**/*.js config/**/*.js plugins/**/*.js",
    "deploy-stage": "gcloud app deploy --project GCP_PROJECT_STAGING_NAME",
    "deploy-production": "gcloud app deploy --project GCP_PROJECT_PROD_NAME",
    "gcp-build": "strapi build"
}
...
```

`strapi-api/config/environments/production/database.json` : 
```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mysql",
        "host": "${process.env.SQL_HOST || '127.0.0.1'}",
        "port": "${process.env.SQL_PORT || 3306}",
        "database": "${process.env.SQL_DATABASE}",
        "username": "${process.env.SQL_USER}",
        "password": "${process.env.SQL_PASSWORD}"
      },
      "options": {
        "ssl": false,
        "min": 0,
        "max": 10000,
        "idleTimeoutMillis": 30000,
        "createTimeoutMillis": 30000,
        "acquireTimeoutMillis": 30000
      }
    }
  }
}
```

Hope this will help :)

**Comment by jopmiddelkamp** [comment]
Het @Lith, did you have to do anything else as specified in your reply?

I just tried to use Google Cloud MySQL the to connect Strapi but I cannot get it to work... Am I doing something wrong here? Does anyone else get it to work?

Package.json: dependencies (partial):
```
    ...
    "knex": "latest",
    "lodash": "^4.17.5",
    "mysql": "^2.17.1",
    "sqlite3": "^4.1.0",
    "strapi": "3.0.0-beta.15",
    "strapi-admin": "3.0.0-beta.15",
    "strapi-hook-bookshelf": "3.0.0-beta.15",
    "strapi-hook-knex": "3.0.0-beta.15",
    ....
```

database.json (staging)

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mysql",
        "host": "${process.env.MYSQL_HOST || '127.0.0.1'}",
        "port": "${process.env.MYSQL_PORT || '3306'}",
        "database": "${process.env.MYSQL_NAME}",
        "username": "${process.env.MYSQL_USERNAME}",
        "password": "${process.env.MYSQL_PASSWORD}"
      },
      "options": {
      }
    }
  }
}
```

app.staging.yaml
```
runtime: nodejs10
service: strapi

env_variables:
  NODE_ENV: staging
  MYSQL_USER: <hidden>
  MYSQL_PASSWORD: <hidden>
  MYSQL_DATABASE: strapi
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: <hidden>:europe-west1:mysql"
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: "<hidden>:europe-west1:mysql"
```

Deployment command

`gcloud app deploy app.staging.yaml --project <hidden> --quiet`

Then the deployment is successful but when I load the page I get a 500 server error.

> Error: Server Error
> The server encountered an error and could not complete your request.
> Please try again in 30 seconds. 

The App Enigine log

>  "GET / HTTP/1.1" 500
>   { Error: connect ECONNREFUSED 127.0.0.1:3306
>       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
>       --------------------
>       at Protocol._enqueue (/srv/node_modules/mysql/lib/protocol/Protocol.js:144:48)
>       at Protocol.handshake (/srv/node_modules/mysql/lib/protocol/Protocol.js:51:23)
>       at Connection.connect (/srv/node_modules/mysql/lib/Connection.js:119:18)
>       at Bluebird (/srv/node_modules/knex/lib/dialects/mysql/index.js:68:18)
>       at Promise._execute (/srv/node_modules/bluebird/js/release/debuggability.js:313:9)
>       at Promise._resolveFromExecutor (/srv/node_modules/bluebird/js/release/promise.js:488:18)
>       at new Promise (/srv/node_modules/bluebird/js/release/promise.js:79:10)
>       at Client_MySQL.acquireRawConnection (/srv/node_modules/knex/lib/dialects/mysql/index.js:63:12)
>       at create (/srv/node_modules/knex/lib/client.js:258:21)
>       at utils_1.tryPromise (/srv/node_modules/tarn/lib/Pool.js:389:34)
>       at Object.tryPromise (/srv/node_modules/tarn/lib/utils.js:53:24)
>       at Promise (/srv/node_modules/tarn/lib/Pool.js:389:17)
>       at new Promise (<anonymous>)
>       at callbackOrPromise (/srv/node_modules/tarn/lib/Pool.js:380:12)
>       at Pool._create (/srv/node_modules/tarn/lib/Pool.js:290:9)
>       at Pool._doCreate (/srv/node_modules/tarn/lib/Pool.js:260:36)
>       at Pool._tryAcquireOrCreate (/srv/node_modules/tarn/lib/Pool.js:211:18)
>       at Pool.acquire (/srv/node_modules/tarn/lib/Pool.js:117:14)
>       at Bluebird.try (/srv/node_modules/knex/lib/client.js:312:43)
>       at tryCatcher (/srv/node_modules/bluebird/js/release/util.js:16:23)
>       at Function.Promise.attempt.Promise.try (/srv/node_modules/bluebird/js/release/method.js:39:29)
>       at Client_MySQL.acquireConnection (/srv/node_modules/knex/lib/client.js:312:26)
>     errno: 'ECONNREFUSED',
>     code: 'ECONNREFUSED',
>     syscall: 'connect',
>     address: '127.0.0.1',
>     port: 3306,
>     fatal: true }
