### ISSUE TITLE
Strapi automatically deletes all components and content types after restarting in docker

### ISSUE THREAD

**Issue by rtatarinov** [strapi/strapi#22239]
I use very simple strapi configuration in my docker
```yml
version: "3.8"

services:
  strapi:
    build: ./admin
    command: sh -c "yarn build && yarn develop"
    restart: unless-stopped
    ports:
      - "127.0.0.1:${ADMIN_PANEL_PORT}:${ADMIN_PANEL_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - network

  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  db:
```
My docker file is
```yml
FROM node:20.10.0-alpine3.18

WORKDIR /app

COPY package.json ./

RUN if [ -f yarn.lock ]; then cp yarn.lock ./; fi

RUN yarn install --non-interactive

COPY . .
```

**Step to reproduce:**
1. run `docker compose up`
2. go to localhost:1337
3. create any component or content type
4. run `docker compose down`
5. run `docker compose up` again
6. go to localhost:1337

Components or content types don't exist at all.
It doesn't relative to `volume` in docker. Because when I create component and down all container I can start only `db` container and see all tables with component. The tables delete only when strapi is started.

Also I use db settings, as `forceMigration: false` and `runMigration: false`. It doesn't work
