### ISSUE TITLE
Incompatibility between Strapi build and PNPM version catalogs

### ISSUE THREAD

**Issue by tretail** [strapi/strapi#22849]
### Node Version

22.13.1

### NPM/Yarn/PNPM Version

9.11.0

### Strapi Version

5.6.0

### Operating System

MacOS

### Database

PostgreSQL

### Javascript or Typescript

Typescript

### Bug Description

Pnpm has introduced Version Catalogs in version 9.5, a way to centralize dependencies at root in the pnpm-workspace.yaml.
That way, it is easier to maintain dependencies accross projects, especially in a monorepo.

For instance, you may have
```yaml
packages:
  - "apps/*"
  - "packages/*"

catalogs:
  react:
    "@types/react": ^18.3.18
    "@types/react-dom": ^18.3.5
    react: ^18.3.1
    react-dom: ^18.3.1
    react-router-dom: ^6.29.0

  strapi:
    "@strapi/strapi": ^5.6.0
    styled-components: ^6.0.0
```

that are used by the consumer project as
```yaml
"dependencies": {
    "@strapi/strapi": "catalog:strapi",
    "react": "catalog:react",
    "react-dom": "catalog:react",
    "react-router-dom": "catalog:react",
    "styled-components": "catalog:strapi"
  },
  "devDependencies": {
    "@types/react": "catalog:react",
    "@types/react-dom": "catalog:react",
```

Running the build will cause errors because Strapi build is unable to handle the version protocol "catalog:":
```
│ [ERROR] 
│ - The declared dependency, react has an invalid version in package.json: catalog:react
│ - The declared dependency, react-dom has an invalid version in package.json: catalog:react
│ - The declared dependency, react-router-dom has an invalid version in package.json: catalog:react
│ - The declared dependency, styled-components has an invalid version in package.json: catalog:strapi
```

### Steps to Reproduce

- Create a pnpm project with Strapi
- Have dependencies handled with pnpm catalog feature
- run `strapi build`

### Expected Behavior

Strapi should be able to be built using pnpm catalogs

### Logs

```shell

```

### Additional information

PNPM Catalogs: https://pnpm.io/catalogs
Strapi code: https://github.com/strapi/strapi/blob/main/packages/core/strapi/src/node/core/dependencies.ts

In the code above:
```typescript
/**
 * Checks the user's project that it has declared and installed the required dependencies
 * needed by the Strapi admin project. Whilst generally speaking most modules will be
 * declared by the actual packages there are some packages where you only really want one of
 * and thus they are declared as peer dependencies – react / styled-components / etc.
 *
 * If these deps are not installed or declared, then we prompt the user to correct this. In
 * V4 this is not a hard requirement, but in V5 it will be. Might as well get people started now.
 */
```

In my opinion, it is a good feature to warn the user about missing peer dependencies; but it is not the goal of Strapi build to enforce it: It is the purpose of package managers and peer dependencies. This create unecessary implicit dependency between Strapi and the package manager used to build.

### Confirmation Checklist

- [x] I have checked the existing [issues](https://github.com/strapi/strapi/issues) for duplicates.
- [x] I agree to follow this project's [Code of Conduct](https://github.com/strapi/strapi/blob/develop/CODE_OF_CONDUCT.md).
