### ISSUE TITLE
Standard Starpi email plugin not working

### ISSUE THREAD

**Issue by LorhanSohaky** [strapi/strapi#3731]
**Describe the bug**
I request to send email but it is not sent.

**Steps to reproduce the behavior**
1. At `strapi-app/plugins/email/controllers/Email.js` replace `await strapi.plugins.email.services.email.send(options, config);` for 
```Javascript
await strapi.plugins['email'].services.email.send({
      to: 'myemail@gmail.com',
      from: 'myemail@gmail.com',
      replyTo: 'myemail@gmail.com',
      subject: 'test',
      text: 'test',
      html: 'test'
    });
```
2. Run `docker-compose up`
3. Go to http://localhost:1337/admin/plugins/users-permissions/roles, enable the public to send email.
4. Make request to http://localhost:1337/email

![image](https://user-images.githubusercontent.com/16273730/62513499-aafa2680-b7f2-11e9-9fdf-d6301a63873f.png)

Enviroment: development
Provider: Sendmail

**System**
- Node.js version: v10.16.1
- NPM version: 6.9.0
- Strapi version: 3.0.0-alpha.26.2
- Database: Mongo
- Operating system: Fedora

My `docker-compose.yml`
``` YML
version: '3'

services:
  api:
    build: .
    image: strapi/strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
    ports:
      - 1337:1337
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
      #- /usr/src/api/strapi-app/node_modules
    depends_on:
      - db
    restart: always

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    restart: always
```
