### ISSUE TITLE
Once new content type is created, cannot enable WYSIWYG for fields.

### ISSUE THREAD

**Issue by iicdii** [strapi/strapi#3766]
**Describe the bug**
Once new content type is created, cannot enable WYSIWYG when you edit text field.
I tested with both following general installtaion using `npm install -g strapi` and `getstarted` example in this repository.

**Steps to reproduce the behavior**
1. Go to Content Type Builder menu.
2. Add new content type with default setting (just name)
3. Add `text` field with default setting (just name)
4. Click save.
5. After server is restarted, go to Content Type Builder again.
6. Edit the `text` field, go to advanced setting.
7. Check to enable WYSIWYG.
8. Click Save, and save again.
9. After restarting, WYSIWYG is not enabled at all.

**Expected behavior**
WYSIWYG should have enabled when you edit content type.

**System**
- Node.js version: v10.15.3
- NPM version: 6.10.2
- Strapi version: 3.0.0-beta.14
- Database: tested both in SQLite and MySQL
- Operating system: macOS Mojave

**Comment by lauriejim** [comment]
Hello! 
I just reproduced your `Steps to reproduce the behavior` and all works well.
Can you try to remove in your database `core_store` the key `plugin_content-manager_schema`
Restart your app, the wysiwyg should appear.

**Comment by soupette** [comment]
Well, instead of deleting that entry you can simply click on the Content Manager tab > click on the desired content type . in the list > select the edit settings.

In the fields list (the one where you can reorder the layout) click on the name of the text field you want to display as WYSIWYG > toggle the button that says display as wysiwyg > save.

**Comment by iicdii** [comment]
Okay. I reproduced with getstarted example again, it works.
but somehow when I do it again with strapi cli, it doesn't work. (in both Quickstart and manual installtion)

This is detail step to reproduce the problem -
### Manual installion with MySQL
1. `npm install strapi@beta -g`
2. `touch docker-compose.yml`
3. `vi docker-compose.yml`, copy and paste down below
```yml
version: '3.1'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test-project
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
    healthcheck:
      test: "mysqladmin -uroot -ppassword ping"
      interval: 3s
      timeout: 1s
      retries: 10
```
4. `docker-compose up`
5. `Command + T` in terminal and `strapi new test-project` in new tab.
7.
```shell
? Choose your installation type 
  Quickstart (recommended) 
❯ Custom (manual settings)
? Choose your default database client 
  sqlite 
  postgres 
❯ mysql
  mongo 
? Database name: (test-project) 
? Host: (127.0.0.1) 
? Port: (3306) 
? Username: admin
? Password: password
? Enable SSL connection: (y/N) N
```
8. `cd test-project && yarn develop`
9. Open chrome, enter `localhost:1337/admin` and create admin account.
10. Click content type builder menu, click add content type.
11. Type 'i18n' in name and save.
12. Add `text` field, type 'en' and save.
13. Save again, server restarts.
14. Click 'en' field, go to advanced settings and enable WYSIWYG.
15. Save again, server restarts.
15. Click 'en' field, go to advanced settings. you can see WYSIWYG is not enabled.
- I uploaded result in https://github.com/iicdii/test-project

### Quickstart Installation with Mongo
1. `npm install strapi@beta -g`
2. `strapi new test-project`
3.
```shell
? Choose your installation type 
❯ Quickstart (recommended) 
  Custom (manual settings)
```
4. `cd test-project && yarn develop`
5. Open chrome, enter `localhost:1337/admin` and create admin account.
6. Click content type builder menu, click add content type.
7. Type 'i18n' in name and save.
8. Add `text` field, type 'en' and save.
9. Save again, server restarts.
10. Click 'en' field, go to advanced settings and enable WYSIWYG.
11. Save again, server restarts.
12. Click 'en' field, go to advanced settings. you can see WYSIWYG is not enabled.

**System**
- Node.js version: v10.15.3
- NPM version: 6.10.2
- Strapi version: 3.0.0-beta.15
- Database: MySQL
- Operating system: macOS Mojave

**Additional context**
- I tried @lauriejim solution, it doesn't work.
- @soupette solution works when this bug appears. But the layout appears when I use strapi@3.0.0-beta.15, not 3.0.0-beta.14.
