### ISSUE TITLE
when go to admin page ,see "Error: read ECONNRESET "

### ISSUE THREAD

**Issue by leedaga** [strapi/strapi#4531]
**1** I installed nodejs  v12.13.0
**2** I use command "npx create-strapi-app lxyapi --quickstart" to create the banckend
**3** Just two warns appeared
"[2019-11-15T02:08:18.035Z] warn The bootstrap function is taking unusually long
to execute (3500 miliseconds).
[2019-11-15T02:08:18.037Z] warn Make sure you call it?"
Create your first administrator � by going to the administration panel at:
┌─────────────────────────────┐
│ http://localhost:1337/admin │
└─────────────────────────────┘
[2019-11-15T02:08:31.306Z] debug HEAD index.html (26 ms) 200
[2019-11-15T02:08:31.312Z] info ⏳ Opening the admin panel...
[2019-11-15T02:08:33.706Z] debug GET index.html (6 ms) 200
[2019-11-15T02:08:33.931Z] debug GET runtime~main.c1955456.js (7 ms) 200
[2019-11-15T02:08:33.933Z] debug GET main.58951efc.chunk.js (5 ms) 200
[2019-11-15T02:08:36.380Z] debug GET /favicon.ico (1 ms) 200
[2019-11-15T02:08:36.523Z] debug GET /users-permissions/init (23 ms) 200
[2019-11-15T02:08:36.553Z] debug GET /admin/init (4 ms) 200
[2019-11-15T02:08:36.693Z] debug GET b4da0df63131b83ddeec1febb5b15374.woff (26 ms) 200
[2019-11-15T02:08:36.717Z] debug GET 482fe0a9e92d9c5ff7fec117ca54c8ae.woff (42 ms) 200
  Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:201:27)

 **Error: read ECONNRESET       at TCP.onStreamRead (internal/stream_base_commons.js:201:27)**
 

**System**
- Node.js version: v12.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.17.5
- Database: SqLite
- Operating system: win2012R2 win2019 

It's OK to use Strapi 3.0.0-beta.17.3 version on win10.

**Comment by derrickmehaffy** [comment]
@leedaga need to know what database type you are using. That ECONNRESET is a database error meaning that strapi couldn't contact the database

**Comment by leedaga** [comment]
@derrickmehaffy tks, i use the defaulte database sqlite,

**Comment by derrickmehaffy** [comment]
That shouldn't even be possible, SQLite is just a file storage, so unless something is going on with permissions.

**Comment by lauriejim** [comment]
Can you make sure you have all write access?

**Comment by leedaga** [comment]
@lauriejim ,I use the admin count to run it, Maybe the code cannot run in win2019, i copy it to another win10 computer,it run again.
i use it for a test project ,tks !

**Comment by lauriejim** [comment]
Are you able to test with another database (mysql or pg)
I need to know if it's related to SQLite or not.

**Comment by bmedici** [comment]
Hello all, same problem here with a Docker install using MongoDB:
```
version: "3"

services:  
  cms:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      PROXY_HOST: strapi.bmconseil.com
      PROXY_PORT: 443
    volumes:
      - strapi-cms2:/srv/app
    ports:
      - "8172:1337"

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - strapi-mongodb2:/data/db
````

Results in a "An error occurred" on the web interface, and nothing in the logs of the Docker service.
https://www.dropbox.com/s/flz950cxdsiqkqf/Screenshot%202020-05-07%2017.40.04.png?dl=0


Furthermore, I cannot go to /admin when using a proxy in front of the installation, as it will always redirect to http://localhost:1337/admin whatever the original URL is. We should not use static port, hostname but get those from HTTP headers instead.
