### ISSUE TITLE
Infinite loading to acesses admin dashboard with docker-compose

### ISSUE THREAD

**Issue by gabrielsoaresm94** [strapi/strapi#4872]
**Describe the bug**
After up the docker containers with the database and strapi, when accessing the route `localhost:1337/admin` with the dashboard there is a load that does not stop.

**Steps to reproduce the behavior**
1. If you do not have Docker and Docker-compose, install with these steps: https://docs.docker.com/get-started/
2. Once installed, create a folder named `project`.
3. Create a docker-compose.yml file.
4. Put the code in * Code snippets * down here in the docker-compose.yml file.
5. In the `project` folder, open the terminal and type the command `docker-compose up`
6. After loading containers, type in browser `localhost: 1337 / admin` to see the problem

**Expected behavior**
Access the `locahost: 1337 / admin` route to be able to create the admin and gain access to the dashboard.

**Code snippets**
The code that I use in docker-compose.yml file:
```
version: '3'

services:
  api:
    depends_on:
      - db
    image: strapi/strapi
    restart: unless-stopped
    # container_name: strapi
    environment:
      APP_NAME: strapi-app
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: project
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: "false"
    ports:
      - 1337:1337
    volumes:
      - ./project/strapi:/usr/src/api/strapi-app

  db:
    image: mysql:5.7
    ports:
      - "33060:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "strapi"
      MYSQL_USER: "strapi"
      MYSQL_PASSWORD: "strapi"
      MYSQL_DATABASE: "project"
    volumes:
      - ./project/db:/var/lib/mysql

#  react:
#    image: front
#    build: ./front
#    ports:
#      - "3000:3000"
```

**System**
- Node.js version: 11.1.0-alpine (Strapi Docker Image)
- NPM version:
- Strapi version: Latest (Strapi Docker Image)
- Database: Mysql 5.7 (Mysql Docker Image)
- Operating system: Ubuntu 18.04.2 LTS 

**Additional context**
I am using the strapi image with this Dockerfile (https://hub.docker.com/r/strapi/strapi/dockerfile) and followed the guidelines in this tutorial: https://www.youtube.com/watch?v=k5KdguLX4NE . I adapted it to a Mysql image, different from MariaDB, which it uses.
