### ISSUE TITLE
Environment Variables not working for development database setup

### ISSUE THREAD

**Issue by Ezeky** [strapi/strapi#5908]
**Describe the bug**
When generating a new strapi setup the database variables are not working in development mode.

**Steps to reproduce the behavior**

1. genrerate a new setup with different database variables example: DATABASE_PASSWORD: 123
2. The build fails cause it cannot communicate with the database.

I am using docker compose this is my setup:
```
version: '3.7'
services:
  strapi:
    image: strapi/strapi
    container_name: strapi
    environment:
      # HOST: 0.0.0.0
      # PORT: 1337
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: 123
    ports:
      - 1337:1337
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
volumes:
    mongo-data:
```

**Expected behavior**
I would assume this should work not only for staging and production but also for deveopment

**Additional context**
Seems to be an issue when generating the config files if you look at 
`/packages/strapi-generate-new/lib/resources/json/database.json.js`
You can see that it will only generate it for production and staging.
