### ISSUE TITLE
Windows 10 docker-compose script does not work with volumes

### ISSUE THREAD

**Issue by ganeshan** [strapi/strapi#6453]
Sample script in [documentation ](https://strapi.io/documentation/v3.x/installation/docker.html) does not work with docker volumes on Windows 10 Docker Desktop with Linux container.
The following script however works:
**docker-compose.yml**
```
version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    links:
      - postgres:postgres
    volumes:
      - app:/srv/app
    ports:
      - '1337:1337'

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes: 
  data:
    external: true
  app:
    external: true

```
However, we need to create the volumes with following commands, before executing the script above.
```
docker volume create --name=app
docker volume create --name=data
```

Now, following command, starts up strapi and postgresql correctly.
`docker-compose up -d`

Hope this helps someone trying docker-compose on Windows 10.
