### ISSUE TITLE
Crashing in develop: strapiInstance.server.destroy is not a function

### ISSUE THREAD

**Issue by anthify** [strapi/strapi#7502]
**Describe the bug**
In develop mode when the app needs to restart, i.e. when  creating a new Content-Type the server crashes. When restarted manually the actions performed are successful.

The crash 💥
```shell
[2020-08-17T16:20:13.714Z] debug POST /content-type-builder/content-types (1122 ms) 201
[2020-08-17T16:20:13.716Z] info The server is restarting
[2020-08-17T16:20:15.067Z] info File created: /db_data/dev@002ddb/adventures.frm
[2020-08-17T16:20:15.068Z] info The server is restarting
/node_modules/strapi/lib/commands/develop.js:87
            strapiInstance.server.destroy(() => {
                                  ^
TypeError: strapiInstance.server.destroy is not a function
    at process.<anonymous> (/node_modules/strapi/lib/commands/develop.js:87:35)
    at process.emit (events.js:215:7)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**My steps to reproduce the behavior**
1. Setup Strapi
2. Setup Docker MySQL 
3. My `docker-compose.yml`
```yml
db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin-password

```
4. My `database.js`
```javascript
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'mysql',
        host: env('DATABASE_HOST', 'localhost'),
        port: env.int('DATABASE_PORT', 3306),
        database: env('DATABASE_NAME', 'dev-db'),
        username: env('DATABASE_USERNAME', 'admin'),
        password: env('DATABASE_PASSWORD', 'admin-password'),
        schema: 'public',
      },
      options: {
        useNullAsDefault: true,
      },
    },
  },
});
```
5. Run start Docker and run `docker-compose up -d` in your shell
6. Run `yarn develop` or `strapi develop`
7.  Go to `localhost:1337/admin` (create account, login)
8. Create Content-Type with some fields
9. Click finish (this is where it crashes)

**Expected behavior**
It shouldn't crash when restarting app.

**System**

- Node.js version: `12.13.0` 
- Yarn version: `1.23
- Strapi version:`3.1.4` 
- Database: `MySQL`
- Operating system: `MacOS Catalina Version 10.15.5`

**Comment by imkrunal** [comment]
Having the same issue but I am using Postgres. It only happens when I try to run it with a docker. Also if I remove the volume from the `docker-compose.yml` it works.

**Comment by derrickmehaffy** [comment]
Hello, I will ping @alexandrebodin and @petersg83 about this issue.

Should this be transfered over to the Docker repo?

**Comment by anthify** [comment]
After reading your message, @imkrunal, I tried to moving the volume to a different directory and it fixed the issue.

### Before
```yml
db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
...
```

### After
```yml
db:
    image: mysql:5.7
    volumes:
      - ../db_data:/var/lib/mysql
...
```

It seems moving the `db_data` folder outside of the strapi application directory fixes this issue.
