### ISSUE TITLE
Cannot connect Strapi app to Redis DB inside Docker

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#8100]
**Describe the bug**
We are trying to Dockerize our Strapi v`3.0.6` app. We are using MongoDB & Redis DB (Redis is only for session storage)

When we run Docker with all 3 containers: `App`, `Mongo` & `Redis`, we cannot connect our Strapi app to Redis DB. 

**Note:** Mongo connection is fine

**Steps to reproduce the behavior**

1. Dockerize Strapi v`3.0.6` with 3 containers: `App`, `Mongo` & `Redis` (Redis is only for session storage)
2. Run the Docker with all 3 containers: `App`, `Mongo` & `Redis`
3. See error: **warn ⚠️  The admin panel is unavailable... Impossible to open it in the browser.**

**Expected behavior**
We should be able to run the App inside Docker connecting to Mongo & Redis databases

**Note:**
1. We are able to run Strapi app locally connecting to Mongo & Redis databases running locally. (Issue is only on Docker)
2. We did Dockerized Strapi v`3.0.0-alpha.23.1` before with MongoDB & Redis DB & it worked fine

**Code snippets**
**Our `docker-compose.yml`:**
```
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: strapi-306:latest

    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi-306
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_USERNAME:
      DATABASE_PASSWORD:

    ports:
      - 1337:1337
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    restart: always

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./docker/db:/docker/db
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    command: ['redis-server', '--bind', 'redis', '--port', '6379']
    restart: always

```

**Our `Dokerfile`:**

```
FROM node:10

WORKDIR /app

COPY . .

COPY env ./

COPY certs ./

COPY package.json ./

RUN npm install

EXPOSE 1337 9229

CMD ["npm","run","start"]
```

**Our `config/database.js`:**

```
module.exports = env => {
  return {
    defaultConnection: 'default',
    connections: {
      default: {
        connector: 'mongoose',
        settings: {
          host: env('DATABASE_HOST', '127.0.0.1'),
          port: env.int('DATABASE_PORT', 27017),
          database: env('DATABASE_NAME', 'strapi-306'),
          username: env('DATABASE_USERNAME', ''),
          password: env('DATABASE_PASSWORD', '')
        },
        options: {
          authenticationDatabase: env('AUTHENTICATION_DATABASE', null),
          ssl: env.bool('DATABASE_SSL', false)
        }
      },
      redis: {
        connector: 'redis',
          host: 'localhost',
          port: '6379',
          settings: {
            client: 'redis'
          },
          options: {
            debug: false
          }
      }
    }
  };
};
```

**Error:**

```
app_1    | 
app_1    |  Project information
app_1    | 
app_1    | ┌────────────────────┬──────────────────────────────────────────────────┐
app_1    | │ Time               │ Tue Sep 29 2020 19:21:59 GMT+0000 (Coordinated … │
app_1    | │ Launched in        │ 4251 ms                                          │
app_1    | │ Environment        │ development                                      │
app_1    | │ Process PID        │ 76                                               │
app_1    | │ Version            │ 3.0.6 (node v10.22.1)                            │
app_1    | └────────────────────┴──────────────────────────────────────────────────┘
app_1    | 
app_1    |  Actions available
app_1    | 
app_1    | One more thing...
app_1    | Create your first administrator 💻 by going to the administration panel at:
app_1    | 
app_1    | ┌─────────────────────────────────────────┐
app_1    | │ https://my_own_host.com/admin │
app_1    | └─────────────────────────────────────────┘
app_1    | 
app_1    | [2020-09-29T19:21:59.941Z] warn ⚠️  The admin panel is unavailable... Impossible to open it in the browser.

```

**System**

- Node.js version: v14.8.0
- NPM version: 6.14.7
- Strapi version: v3.0.6
- Database: Mongo & Redis(for Session)
- Operating system: MAC

**Additional context**
