### ISSUE TITLE
Strapi won't start after upgrading version

### ISSUE THREAD

**Issue by seguelador** [strapi/strapi#8335]
**Describe the bug**
My Strapi app has been running on Docker (https://strapi.io/blog/how-to-run-a-strapi-dev-stack-with-docker-compose) for a couple of months already, and it's been alright. Then, yesterday I upgraded it from version **3.0.0-beta.18.7** (which was installed by default by strapi) to **3.1.7**, following this guide: https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.0.x-to-3.1.x.html

I followed all the steps in the mentioned guide but the step 4 (I'm not using any custom plugins)

After doing so, I started my app as usual and faced this error:

```
bi-sitio-publico-cms | Starting your app...
db-sitio-publico-cms | 2020-10-14 14:49:21.819 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-sitio-publico-cms | 2020-10-14 14:49:21.819 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-sitio-publico-cms | 2020-10-14 14:49:21.824 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-sitio-publico-cms | 2020-10-14 14:49:21.885 UTC [24] LOG:  database system was shut down at 2020-10-14 14:49:02 UTC
db-sitio-publico-cms | 2020-10-14 14:49:21.914 UTC [1] LOG:  database system is ready to accept connections
bi-sitio-publico-cms | [2020-10-14T14:49:39.202Z] debug ⛔️ Server wasn't able to start properly.
bi-sitio-publico-cms | [2020-10-14T14:49:39.206Z] error TypeError: Cannot convert undefined or null to object
bi-sitio-publico-cms |     at Function.values (<anonymous>)
bi-sitio-publico-cms |     at Object.load (/srv/app/node_modules/strapi-database/lib/connector-registry.js:17:39)
bi-sitio-publico-cms |     at DatabaseManager.initialize (/srv/app/node_modules/strapi-database/lib/database-manager.js:32:21)
bi-sitio-publico-cms |     at Strapi.load (/srv/app/node_modules/strapi/lib/Strapi.js:308:19)
bi-sitio-publico-cms |     at async Strapi.start (/srv/app/node_modules/strapi/lib/Strapi.js:190:9)
bi-sitio-publico-cms exited with code 1
```

**Steps to reproduce the behavior**

1. Having Strapi v3.0.0-beta.18.7, upgrade it to 3.1.7 following the upgrading guide
2. Face the error :D

**Expected behavior**
I expected the app to run smooth and fast as it used to do before

**Code snippets**
- Here is a portion of my package.json file (Also, I had an issue with Sharp and "darwin-x64' binaries cannot be used on the 'linux-x64' platform" so I had to install it manually.
```
"dependencies": {
 12     "apollo-server-koa": "^2.17.0",
 13     "knex": "<0.20.0",
 14     "pg": "latest",
 15     "sharp": "^0.26.1",
 16     "strapi": "3.1.7",
 17     "strapi-admin": "3.1.7",
 18     "strapi-connector-bookshelf": "3.1.7",
 19     "strapi-plugin-content-manager": "3.1.7",
 20     "strapi-plugin-content-type-builder": "3.1.7",
 21     "strapi-plugin-documentation": "3.1.7",
 22     "strapi-plugin-email": "3.1.7",
 23     "strapi-plugin-graphql": "3.1.7",
 24     "strapi-plugin-upload": "3.1.7",
 25     "strapi-plugin-users-permissions": "3.1.7",
 26     "strapi-utils": "3.1.7"
 27   },
```

- My docker-compose
```
version: "3"

services:
  strapi:
    container_name: ${APP_CONTAINER_NAME}
    image: strapi/strapi
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=${POSTGRES_PORT}
      - DATABASE_NAME=${POSTGRES_DB_NAME}
      - DATABASE_USERNAME=${POSTGRES_USER}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_AUTHENTICATION_DATABASE=strapi
    ports:
      - 1337:1337
    volumes:
      - .:/srv/app
    links:
      - database

  database:
    image: postgres:10.6
    restart: always
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      SERVICE: database
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ~/.docker-volumes/bi-sitio-publico-cms2/postgresql/data:/var/lib/postgresql/data

```

**System**

- Node.js version: In my laptop: v14.13.0 (though I'm using Docker)
- NPM version:
- Strapi version: v3.0.0-beta.18.7 (It was installed by Strapi by default following the Getting Started guide)
- Database: PostgreSQL
- Operating system: Linux (Ubuntu I guess)

By the way, I'm intending to upgrade Strapi to 3.2 (I want to use the Draft and Publish feature).
