### ISSUE TITLE
createTelemetry crashes on none-shell host

### ISSUE THREAD

**Issue by hxhieu** [strapi/strapi#8893]
### Describe the bug

When hosting Strapi on a none-shell host such as Google [distroless](https://github.com/GoogleContainerTools/distroless) container, the start up script will crash because `node-machine` is executing a shell script to get the machine ID.  

### Steps to reproduce the behavior

Like above

### Expected behavior

Not crashing

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 12
- NPM version: yarn v1.22.0
- Strapi version: 3.3.4
- Database: sqlite
- Operating system: Windows 10

### Additional context

According to this https://strapi.io/documentation/v3.x/getting-started/usage-information.html#commitment-to-our-users-data-collection, we can opt-out the telemetry but even that the code still try to execute `node-machine` get ID.
It should stop doing that if the consumer has chosen to opt-out
```
// lib/sevices/metrics/sender/js line 25

let deviceId = 'unknown'
// machineIdSync() will not work on none-shell host
// so we should disable it when opt-out telemetry
// https://strapi.io/documentation/v3.x/getting-started/usage-information.html#commitment-to-our-users-data-collection
if (uuid){
    deviceId = machineIdSync();
}
```

**Comment by derrickmehaffy** [comment]
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/strapi-deployment-in-aws-amplify/1642/9

**Comment by hxhieu** [comment]
Thanks @derrickmehaffy

**Comment by kicaal** [comment]
hello! Is there any solution? i have delete uuid from package json and the /bin/sh: hostname: command not found it continues to appear in the amplify deploy…
is there any other way? thanks!!

```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - cd cms
        - npm install
    build:
      commands:
        - npm run build
    postBuild:
        commands:
        - npm run start
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
