### ISSUE TITLE
Strapi 3.4.2, 3.4.1 docker-compose fails due to `sharp` build error: `fatal error: vips/vips8: No such file or directory`

### ISSUE THREAD

**Issue by virgil9306** [strapi/strapi#9114]
### Describe the bug

* On OSX Catalina and Strapi `3.4.1` and Strapi `3.4.2` docker images, running `strapi/strapi` in docker-compose fails.
* This error did not occur previously (`3.1.5` was the last version I used before I saw this error happen).
* Since [`strapi-plugin-upload`](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/package.json) uses `sharp` I wonder if that may be related.

Here is the error message:

```
> sharp@0.26.2 install /srv/app/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.0/libvips-8.10.0-linux-x64.tar.br
ERR! sharp EPERM: operation not permitted, link '/srv/app/node_modules/sharp/vendor/8.10.0/include/pnglibconf.h' -> '/srv/app/node_modules/sharp/vendor/8.10.0/include/libpng16/pnglibconf.h'
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
make: Entering directory '/srv/app/node_modules/sharp/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
  COPY Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:24:22: fatal error: vips/vips8: No such file or directory
 #include <vips/vips8>
                      ^
compilation terminated.
sharp.target.mk:139: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: Leaving directory '/srv/app/node_modules/sharp/build'
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.14.154-boot2docker
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /srv/app/node_modules/sharp
gyp ERR! node -v v12.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN strapi-connector-bookshelf@3.4.1 requires a peer of knex@^0.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN @buffetjs/utils@3.3.3 requires a peer of yup@^0.27.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.5.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.26.2 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.26.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-13T11_41_41_991Z-debug.log
```

### Steps to reproduce the behavior

1. Using the above `docker-compose.yaml` on 

### Expected behavior

Previously the build succeeded here.

### Screenshots

N/A

### Code snippets

See "Additional Context" at the end

### System

- Node.js version: Using `strapi/strapi` so same version as that (unsure). Local system is running Node `v12.18.3`
- NPM version: Using `strapi/strapi` so same version as that (unsure). Local system is running npm `v6.14.6`
- Strapi version: 3.4.2, 3.4.1
- Database: MariaDB
- Operating system: OSX Catalina latest updates

### Additional context

* This is not an M1 machine. Also, since I am using the Docker image `strapi/strapi` I cannot try the steps linked in the latest documentation: https://github.com/lovell/sharp/issues/2460 -- but the error is the same. Thus maybe the `strapi/strapi` docker image should also simply install `vips` and maybe that would fix it?
* I did not notice this error when using `strapi/base` to use a `Dockerfile` to build a Strapi image. I only noticed this issue when running in `docker-compose` using `strapi/strapi`.
* I changed the versions manually in `docker-compose.yaml` to `3.4.2`, `3.4.1` and reproduced the error each time.
* `docker-compose.yaml` file:

```
version: '3'

services:
  strapi:
    container_name: cms-strapi
    image: strapi/strapi:latest
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    volumes:
      - ${PWD}/app:/srv/app
    depends_on:
      - db

  db:
    container_name: cms-db
    image: bitnami/mariadb:latest
    restart: always
    volumes:
      - ${PWD}/db:/var/lib/mysql
    environment:
      - MARIADB_USER=strapi
      - MARIADB_PASSWORD=strapi
      - MARIADB_DATABASE=strapi
      - MARIADB_ROOT_PASSWORD=strapi
```
