### ISSUE TITLE
Configure Strapi backend URL after build

### ISSUE THREAD

**Issue by ath88** [strapi/strapi#9395]
### Please describe your feature request
- [X] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

It would be great to be able to configure the Strapi backend URL after the admin bundle has been built.

### Why is it needed?

It will allow for a more flexible deployment, using the same build artefact for multiple deployments, when using separate URLs for backend and frontend, which we do. This will also make it easier to make a pre-built docker image.

### Suggested solution(s)

I suggest making it possible to specify a URL where the backend URL can be fetched. On deployment, a file containing the URL could be placed on the specified URL, which will let Strapi determine the URL for the backend on initialization. 

For example, the first thing the Strapi admin bundle would do could be a GET request to `/backend-url` which could respond with a URL to be used. Then on deployment, all we need to do is to deploy the `backend-url`-file along with the bundle.

**Comment by derrickmehaffy** [comment]
Hi @ath88 

How do you purpose we solve the remote admin deployment? As many users don't use Strapi to serve the admin panel and instead build it and deploy it statically on another server (especially when scaling strapi horizontally where a single Nginx instance can serve the admin then proxy backend requests)

**Comment by ath88** [comment]
I am not sure I understand your question. Solve the remote admin deployment?

Ill try to elaborate on the problem this PR solves - perhaps that answers your question.

This solves a problem that only occurs when the admin panel is deployed separately from the backend.

Currently, the remote address for the backend must be known when building the Strapi admin panel. That means that when we deploy the admin panel and the backend separately, we need to know the domain for the backend, way earlier than when deployment happens. Many organisations have CI pipelines that doesn't allow the build-process to know anything about the actual deployment. This is the essence of the problem.

My solution to this is that during deployment, a file can be added to be served along with the bundle (eg. through nginx). For now, the file must contain the absolute URL for the deployed backend and nothing else. I did consider whether this should be a json-file instead for easier extension, but I decided that any other configuration could be done through API access to the backend.

I hope that answered your question. :)

**Comment by derrickmehaffy** [comment]
> Many organisations have CI pipelines that doesn't allow the build-process to know anything about the actual deployment.

Then how would the file be set? (What I'm referring to here is processes that don't differ between build and deploy, which we at Strapi use ourselves).

I just want to get some picture of how you think it would normally be handled because these processes and recommendations will have to be documented.

**Comment by ath88** [comment]
We deploy via Kubernetes and have something like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-frontend
  labels:
    app: strapi-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strapi-frontend
  template:
    metadata:
      labels:
        app: strapi-frontend
    spec:
      containers:
      - name: strapi-frontend
        image: eu.gcr.io/us/strapi-frontend:v1.0.0
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - mountPath: /usr/share/nginx/html/backend-url
          name: strapi-frontend-config
          subPath: backend-url
      volumes:
      - name: strapi-frontend-config
        configMap:
          name: strapi-frontend
          items:
          - key: backend-url
            path: backend-url
```
... where the backend-url is a file containing the URL, evidently.

If you have build and deploy as the same process, you can simply use the old method. The BackendUrlFetcher is transparent in that way.
