### ISSUE TITLE
error: relation core_store does not exist

### ISSUE THREAD

**Issue by aditya-mitra** [strapi/strapi#9471]
### Describe the bug

I am running strapi in a docker container attached to a postgres db.
The strapi container would always fail to start.

Neither `strapi start` nor `strapi develop` would work.

### Steps to reproduce the behavior

1. Run a strapi docker container with postgres docker container also.

### Expected behavior

Strapi would start without fail

### Screenshots

Even **`strapi develop`** would not work.

![image](https://user-images.githubusercontent.com/55396651/108632153-6cd75d00-7493-11eb-8a45-b48e2c3d8103.png)

Log of operations in the postgres database

![image](https://user-images.githubusercontent.com/55396651/108632593-cf315d00-7495-11eb-9743-98a88a588825.png)

### Code snippets

I can produce more code snippets if asked to.

**docker-compose.yml**
```yml
version: "3"

services:
    db:
        container_name: pgdb
        image: postgres:12-alpine
        restart: on-failure
        environment:
            POSTGRES_DB: strapi_db
            POSTGRES_USER: strapi_user
            POSTGRES_PASSWORD: strapi_webdev
        volumes:
            - ./pgdocker:/var/lib/postgresql/data
        ports:
            - 5432:5432
        network_mode: host

    cms:
        container_name: cmsbackend
        build: ./cms
        environment:
            DATABASE_NAME: strapi_db
            DATABASE_HOST: localhost
            DATABASE_USERNAME: strapi_user
            DATABASE_PASSWORD: strapi_webdev
            DATABASE_PORT: 5432
        depends_on:
            - db
        ports:
            - 9000:9000
        network_mode: host
        restart: on-failure
```

I am also pasting the code of `database.js` file:
```js
const productionConfig = ({ env }) => {

	return {
		defaultConnection: 'default',
		connections: {
			default: {
				connector: 'bookshelf',
				settings: {
					client: 'postgres',
					host: env('DATABASE_HOST', 'localhost'),
					database: env('DATABASE_NAME', 'strapi_db'),
					port: env.int('DATABASE_PORT', 5432),
					username: env('DATABASE_USERNAME', 'strapi_user'),
					password: env('DATABASE_PASSWORD', 'strapi_webdev'),
					ssl: false
				},
			},
		},
	};
};
export default productionConfig;
```

### System

- Node.js version:  v12
- NPM version: v6
- Strapi version:  3.4.2
- Database: postgres-12
- Operating system: node:12-alpine (docker container)

### Additional context

I have tried this on several virtual machines but still it ain't resolving.
